- Google.Api.Generator.Tests/ProtoTest.cs
- Google.Api.Generator/CodeGenerator.cs
- Google.Api.Generator/Generation/ServiceCodeGenerator.cs
- Google.Api.Generator/Generation/ServiceDetails.cs
- Google.Api.Generator/Generation/ServiceSettingsCodeGenerator.cs
- Google.Api.Generator/Generation/SourceFileContext.cs
- Google.Api.Generator/Google.Api.Generator.csproj
- Google.Api.Generator/ProtoUtils/ProtoConsts.cs
- Google.Api.Generator/RoslynUtils/Modifier.cs
- Google.Api.Generator/RoslynUtils/RoslynBuilder.cs
- Google.Api.Generator/Utils/Disposable.cs
- Google.Api.Generator/Utils/Typ.cs
Just enough implemented to generate the structure of the client Settings class, with a test.
Code formatting not yet implemented, which is why the test can't use the Roslyn parser yet to check the result.
> Initial code generation

- Google.Api.Generator.Tests/Google.Api.Generator.Tests.csproj
- Google.Api.Generator.Tests/ProtoTest.cs
- Google.Api.Generator.Tests/WhitespaceFormatterTest.cs
- Google.Api.Generator/CodeGenerator.cs
- Google.Api.Generator/Formatting/CodeFormatter.cs
- Google.Api.Generator/Formatting/WhitespaceFormatter.cs
- Google.Api.Generator/RoslynUtils/RoslynExtensions.cs
Proto test can now use Roslyn to check generated code.
> Add code whitespace formatter, with test

- Google.Api.Generator.Tests/ProtoTest.cs
- Google.Api.Generator.Tests/ProtoTests/ResourceNames/ResourceNamesClient.cs
It used to allow extra lines in the generated output, which were not present in the expected code. Now it only accepts generated code that is exactly as in the expected code blocks.
> Fix generator test

- Google.Api.Generator.Tests/ProtoTest.cs
- Google.Api.Generator.Tests/ProtoTests/ResourceNames/ResourceNamesClient.cs
- Google.Api.Generator.Tests/ProtoTests/ResourceNames/ResourceNamesResourceNames.cs
- Google.Api.Generator/Generation/ResourceNamesGenerator.cs
- Google.Api.Generator/Generation/SourceFileContext.cs
- Google.Api.Generator/ProtoUtils/ResourceDetails.cs
- Google.Api.Generator/Utils/SystemExtensions.cs
Fix casing of resource-name class Parse() method parameter
Fix name of reosurce-name property when the underlying property is named 'Name'
Improve test output when proto test fails
> Fix naming errors

- Google.Api.Generator.Tests/ProtoTests/Lro/LroResourceNames.cs
- Google.Api.Generator.Tests/ProtoTests/Paginated/PaginatedResourceNames.cs
- Google.Api.Generator.Tests/ProtoTests/ResourceNames/ResourceNames.proto
- Google.Api.Generator.Tests/ProtoTests/ResourceNames/ResourceNamesResourceNames.cs
- Google.Api.Generator.Tests/ProtoTests/ServerStreaming/ServerStreamingResourceNames.cs
- Google.Api.Generator/Generation/ResourceNamesGenerator.cs
Include the resource-name generated code in all tests; I realised it could be frustrating later if these files fall behind the latest code-gen.
> Handle resource-name id suffixes correctly

- Google.Api.Generator.Tests/Google.Api.Generator.Tests.csproj
- Google.Api.Generator.Tests/ProtoTest.cs
- Google.Api.Generator.Tests/ProtoTests/Basic/BasicClient.cs
- Google.Api.Generator.Tests/ProtoTests/Basic/BasicClientSnippets.g.cs
- Google.Api.Generator.Tests/ProtoTests/Lro/LroClient.cs
- Google.Api.Generator.Tests/ProtoTests/MethodSignatures/MethodSignaturesClient.cs
- Google.Api.Generator.Tests/ProtoTests/Paginated/PaginatedClient.cs
- Google.Api.Generator.Tests/ProtoTests/ResourceNames/ResourceNamesClient.cs
- Google.Api.Generator.Tests/ProtoTests/ServerStreaming/ServerStreamingClient.cs
- Google.Api.Generator.Tests/ProtoTests/Snippets/Snippets.proto
- Google.Api.Generator.Tests/ProtoTests/Snippets/SnippetsClient.cs
- Google.Api.Generator.Tests/ProtoTests/Snippets/SnippetsClientFakes.cs
- Google.Api.Generator.Tests/ProtoTests/Snippets/SnippetsClientSnippets.g.cs
- Google.Api.Generator.Tests/ProtoTests/Snippets/SnippetsResourceNames.cs
- Google.Api.Generator.Tests/WhitespaceFormatterTest.cs
- Google.Api.Generator/Formatting/WhitespaceFormatter.cs
- Google.Api.Generator/Generation/SnippetCodeGenerator.cs
- Google.Api.Generator/RoslynUtils/RoslynConverters.cs
Two commits. The first one is the affects of a small code-formatter change.
The support for defaults in snippets is in the seconds commit.
> Support all defaults, including resource-names, in snippets

- Google.Api.Generator.Tests/ProtoTests/Basic/BasicClientSnippets.g.cs
- Google.Api.Generator.Tests/ProtoTests/Snippets/SnippetsClientSnippets.g.cs
- Google.Api.Generator/Formatting/WhitespaceFormatter.cs
- Google.Api.Generator/Generation/SourceFileContext.cs
Using statements in snippets need to be within the namespace, not at the top-level of the file.
Test the entire snippet test output file, rather thatn just a portion of it.
> Fix using directive location in snippets

- Google.Api.Generator.Tests/ProtoTests/UnitTests/Testing.UnitTests.Tests/UnitTestsClientTest.g.cs
- Google.Api.Generator.Tests/ProtoTests/UnitTests/Testing.UnitTests/UnitTestsClient.cs
- Google.Api.Generator.Tests/ProtoTests/UnitTests/UnitTests.proto
- Google.Api.Generator.Tests/ProtoTests/UnitTests/UnitTestsFakes.cs
- Google.Api.Generator/Generation/UnitTestCodeGeneration.cs
This does not add support for testing LRO methods; it just allows tests within services that *contain* LRO methods to work properly.
Unit-test generation is now at parity with the existing generator
> Support unit-testing on services that contain LRO clients

- docker-entrypoint.sh
To conform to naming convention specificed in https://aip.dev/client-libraries/4210
> Minor fix to protoc invokation in docker

- Google.Api.Generator/ProtoUtils/ResourceDetails.cs
After discussions with Luke, we'll require the parent pattern to be explicitly defined within an existing resource. No autogeneration of parent resource-names will be supported.
This decision can be revisited if necessary.
> Update child_type error if parent doesn't exist

- Google.Api.Generator.Tests/ProtoTests/CommonResource/CommonResourceDef.proto
- Google.Api.Generator/CodeGenerator.cs
- Google.Api.Generator/Generation/ResourceNamesGenerator.cs
Fixes the problem as seen in spanner.
Where a partial class not generated when the class is a resource-message, and the resource-name class is defined elsewhere and configured in the common-resource-config file.
> Fix partial generation

- Google.Api.Generator.Tests/ProtoTests/GrpcServiceConfig/GrpcServiceConfig.json
- Google.Api.Generator.Tests/ProtoTests/GrpcServiceConfig/Testing.GrpcServiceConfig/GrpcServiceConfigClient.g.cs
- Google.Api.Generator/Generation/MethodDetails.cs
This used to produce very ugly output for unrepresentable numbers - e.g. 1.3 would be output as 1.2999999523162842
> Fix unfortunate float->double conversion

- Google.Api.Generator/Generation/MethodDetails.cs
We mustn't treat the operation-returning methods *in LRO itself* as LRO methods.
> Support microgeneration of Google.LongRunning

- Google.Api.Generator.Tests/ProtoTests/Paginated/Paginated.proto
- Google.Api.Generator.Tests/ProtoTests/Paginated/PaginatedFakes.cs
- Google.Api.Generator.Tests/ProtoTests/Paginated/Testing.Paginated.Snippets/PaginatedClientSnippets.g.cs
- Google.Api.Generator.Tests/ProtoTests/Paginated/Testing.Paginated/PaginatedClient.g.cs
- Google.Api.Generator/Generation/SnippetCodeGenerator.cs
Fixes #198.
2 lines of production code change (+ a typo fix), hundreds of lines of test code change...
> Apply pagination named arguments corner case to resource name overloads

- Google.Api.Generator.Tests/ProtoTests/Paginated/Paginated.proto
- Google.Api.Generator.Tests/ProtoTests/Paginated/Testing.Paginated.Snippets/PaginatedClientSnippets.g.cs
- Google.Api.Generator.Tests/ProtoTests/Paginated/Testing.Paginated/PaginatedClient.g.cs
- Google.Api.Generator/Generation/ServiceCodeGenerator.cs
Fixes #203 
Prevents multiple identical partial classes being generate when more than one method returns the same paginated response type.
> Fix pagination partial generation

- Google.Api.Generator.Tests/ProtoTests/Snippets/Testing.Snippets/SnippetsResourceNames.g.cs
- Google.Api.Generator.Tests/ProtoTests/UnitTests/Testing.UnitTests/UnitTestsResourceNames.g.cs
- Google.Api.Generator/ProtoUtils/ResourceDetails.cs
Fixes #205.
This would be a breaking change if we had any such resources, but it looks like we don't (yet).
(I have another commit to add a resource-name-accepting method test, but it looks like that's redundant.)
> Fix resource property for wildcard resource fields called "name"

- Google.Api.Generator.Tests/ProtoTests/Basic/Testing.Basic/BasicClient.g.cs
- Google.Api.Generator.Tests/ProtoTests/Keywords/Testing.Keywords/KeywordsClient.g.cs
- Google.Api.Generator.Tests/ProtoTests/UnitTests/Testing.UnitTests/UnitTestsClient.g.cs
- Google.Api.Generator/Generation/ServiceAbstractClientClassCodeGenerator.cs
We now just expose three factory methods:
- An internal one accepting a CallInvoker and settings; this is as it was before, just internal.
- A parameterless Create method, which uses default credentials, endpoint and settings
- A CreateAsync method accepting an optional cancellation token, which uses default credentials, endpoint and settings
For anything else, we recommend the use of the client builder, which has far more flexibility than any reasonable set of methods could.
Note that the existence of a cancellation token for CreateAsync is new, and IIRC the guts of Google.Api.Auth don't fully support it yet, but it's worth putting in now rather than later.
Fixes #207.
> Simplify the abstract client factory methods.

- Google.Api.Generator/Generation/SnippetCodeGenerator.cs
- Google.Api.Generator/Generation/UnitTestCodeGeneration.cs
This is effectively left over work from https://github.com/googleapis/gapic-generator-csharp/commit/99f02340d3d9000d16a516c84ffd5317145da672
It's slightly worrying that no tests have changed here.
> Don't generate tests/snippets for IResourceName overloads

- Google.Api.Generator.Tests/ProtoTests/ChildResource/Testing.ChildResource/ChildResourceResourceNames.g.cs
- Google.Api.Generator.Tests/ProtoTests/ResourceNames/Testing.ResourceNames/ResourceNamesResourceNames.g.cs
- Google.Api.Generator.Tests/ProtoTests/UnitTests/Testing.UnitTests/UnitTestsResourceNames.g.cs
- Google.Api.Generator/Generation/ResourceNamesGenerator.cs
Fixes #216.
I don't think we should agonize too much on the precise wording, as oneofs don't exist in the next major version.
> Generate XML comments for OneOf resource name constructors

- Google.Api.Generator.Tests/ProtoTests/Snippets/Snippets.proto
- Google.Api.Generator.Tests/ProtoTests/Snippets/SnippetsClientFakes.cs
- Google.Api.Generator.Tests/ProtoTests/Snippets/Testing.Snippets.Snippets/SnippetsClientSnippets.g.cs
- Google.Api.Generator.Tests/ProtoTests/Snippets/Testing.Snippets/SnippetsResourceNames.g.cs
- Google.Api.Generator/Generation/SnippetCodeGenerator.cs
> Failing test for snippets for repeated resource names in signatures

- Google.Api.Generator.Tests/ProtoTests/Basic/Testing.Basic/BasicClient.g.cs
- Google.Api.Generator.Tests/ProtoTests/Deprecated/Testing.Deprecated/DeprecatedClient.g.cs
- Google.Api.Generator.Tests/ProtoTests/Keywords/Testing.Keywords/KeywordsClient.g.cs
- Google.Api.Generator.Tests/ProtoTests/UnitTests/Testing.UnitTests/UnitTestsClient.g.cs
- Google.Api.Generator/Generation/ServiceBuilderCodeGenerator.cs
- Google.Api.Generator/RoslynUtils/RoslynExtensions.cs
This will make implementing emulator support simpler, for example.
An alternative possibly design would be to have a partial method
"returning" (via a ref parameter) another builder of the same type.
We could then, then we could call Build or BuildAsync on that
builder (if not null). This would mean only implementing a single
partial method in partial classes - but would prohibit any
customization requiring asynchrony.
The scheme in this commit is still not massively onerous for partial
class implementers, but gives more freedom for future expansion.
Note that all of this can change in the generator later, in that
it's a breaking change for generator consumers, but not for end user
developers, as the public API surface remains the same
(Build/BuildAsync).
> Allow partial class interception of client builder methods

- Google.Api.Generator.Tests/ProtoTests/Keywords/Keywords.proto
- Google.Api.Generator.Tests/ProtoTests/Keywords/KeywordsFakes.cs
- Google.Api.Generator.Tests/ProtoTests/Keywords/Testing.Keywords.Snippets/KeywordsClientSnippets.g.cs
- Google.Api.Generator.Tests/ProtoTests/Keywords/Testing.Keywords.Tests/KeywordsClientTest.g.cs
- Google.Api.Generator.Tests/ProtoTests/Keywords/Testing.Keywords/KeywordsClient.g.cs
- Google.Api.Generator/ProtoUtils/ProtoExtensions.cs
> Fix field naming when the same name as the enclosing message

- Google.Api.Generator.Tests/ResourceDetailsTest.cs
- Google.Api.Generator/ProtoUtils/ResourceDetails.cs
This changes the logic for "parent pattern" to be broadly:
- Determine the segments of the pattern by splitting on slash
- Remove either the last two segments (if the last segment is
a parameter, e.g. "{project}") or just the last segment otherwise
- Join the remaining segments together again with a slash separator
(Note that I'm waiting for confirmation this is all correct from multiple sources before merging.)
> Update parent pattern handling to cope with singleton resources

- Google.Api.Generator.Tests/ProtoTests/Basic/Testing.Basic/BasicClient.g.cs
- Google.Api.Generator.Tests/ProtoTests/ChildResource/Testing.ChildResource/ChildResourceResourceNames.g.cs
- Google.Api.Generator.Tests/ProtoTests/Deprecated/Testing.Deprecated/DeprecatedClient.g.cs
- Google.Api.Generator.Tests/ProtoTests/Keywords/Testing.Keywords/KeywordsClient.g.cs
- Google.Api.Generator.Tests/ProtoTests/Keywords/Testing.Keywords/KeywordsResourceNames.g.cs
- Google.Api.Generator.Tests/ProtoTests/Lro/Testing.Lro/LroResourceNames.g.cs
- Google.Api.Generator.Tests/ProtoTests/Paginated/Testing.Paginated/PaginatedResourceNames.g.cs
- Google.Api.Generator.Tests/ProtoTests/ResourceNameSeparator/Testing.ResourceNameSeparator/ResourceNameSeparatorResourceNames.g.cs
- Google.Api.Generator.Tests/ProtoTests/ResourceNames/Testing.ResourceNames/ResourceNamesResourceNames.g.cs
- Google.Api.Generator.Tests/ProtoTests/ServerStreaming/Testing.ServerStreaming/ServerStreamingResourceNames.g.cs
- Google.Api.Generator.Tests/ProtoTests/Snippets/Testing.Snippets/SnippetsResourceNames.g.cs
- Google.Api.Generator.Tests/ProtoTests/UnitTests/Testing.UnitTests/UnitTestsClient.g.cs
- Google.Api.Generator.Tests/ProtoTests/UnitTests/Testing.UnitTests/UnitTestsResourceNames.g.cs
- Google.Api.Generator/Generation/ResourceNamesGenerator.cs
- Google.Api.Generator/Generation/ServiceBuilderCodeGenerator.cs
We still use inheritdoc for ==, != and Equals - those don't seem to
cause docfx issues, for whatever reason.
The documentation isn't always *exactly* what would be inherited -
I've simplified it in a couple of places - but it's close enough.
Fixes #248.
> Use explicit docs instead of inheritdoc in most places

- Google.Api.Generator.Tests/ProtoTests/GrpcServiceConfig/GrpcServiceConfig.json
- Google.Api.Generator.Tests/ProtoTests/GrpcServiceConfig/GrpcServiceConfig.proto
- Google.Api.Generator.Tests/ProtoTests/GrpcServiceConfig/Testing.GrpcServiceConfig/GrpcServiceConfigClient.g.cs
- Google.Api.Generator/Generation/MethodDetails.cs
- Google.Api.Generator/Generation/ServiceDetails.cs
> Support retry with only timeout specified

- rules_csharp_gapic/csharp_gapic_pkg.bzl
- Updates the outgoing `tar` command to -C into `out_tar`'s containing directory, so that final archive only contains a single directory matching the rule name.
- Remove `out_dir` from declared outputs so that Bazel understands that the rule only produces a single output file. Otherwise, it interprets the output `depset` as producing multiple artifacts (rendering certain operators like `$<` unusable).
> Fixes for output of `csharp_gapic_assembly_pkg` rule

- Google.Api.Generator/Generation/SnippetCodeGenerator.cs
- Google.Api.Generator/Generation/UnitTestCodeGeneration.cs
This involves unfortunate duplication, but I suspect that can't be
avoided without a bit more disruption. (Ideally the
SnippetCodeGenerator, UnitTestCodeGenerator and
could use ResourceNamesGenerator as the one true source of
information about what would be generated, but that would be a big
change.)
No tests yet - there's no *simple* place to add a test for this.
Suggestions welcome, including "it's not worth it for this case".
> Fix test and snippet generation for constant patterns

- Google.Api.Generator.Tests/ProtoTest.cs
- Google.Api.Generator.Tests/ProtoTests/ResourceNames/ResourceNamesFakes.cs
- Google.Api.Generator.Tests/ProtoTests/ResourceNames/Testing.ResourceNames.Snippets/ResourceNamesClientSnippets.g.cs
- Google.Api.Generator.Tests/ProtoTests/ResourceNames/Testing.ResourceNames.Tests/ResourceNamesClientTest.g.cs
- Google.Api.Generator.Tests/ProtoTests/ResourceNames/Testing.ResourceNames/ResourceNamesClient.g.cs
This does not yet test the new 'parameterless pattern' code; that change will be in a follow-up PR
> Enable snippets and unittests for resource-name tests

- Google.Api.Generator.Tests/ProtoTests/Basic/Testing.Basic/Testing.Basic.csproj
- Google.Api.Generator.Tests/ProtoTests/Lro/Testing.Lro/Testing.Lro.csproj
- Google.Api.Generator/Generation/CsProjGenerator.cs
And add a direct reference to Google.Protobuf, to get the latest version as required by the latest protoc-generated files
> Update deps in generated csproj files

- BUILD.bazel
- repositories.bzl
- rules_csharp_gapic/BUILD.bazel
- rules_csharp_gapic/csharp_compiler.bzl
- rules_csharp_gapic/csharp_compiler_repo.bzl
Required to run the latest generator version due to recent use of project-reference
> Rewrite C# bazel rules

- Google.Api.Generator.Rest.Tests/GoldenTestData/Google.Apis.Storage.v1/Google.Apis.Storage.v1.cs
- Google.Api.Generator.Rest.Tests/GoldenTestData/Google.Apis.Storage.v1/discovery.json
- Google.Api.Generator.Rest/CodeGenerator.cs
- Google.Api.Generator.Rest/Models/AuthScope.cs
- Google.Api.Generator.Rest/Models/DataModel.cs
- Google.Api.Generator.Rest/Models/DataPropertyModel.cs
- Google.Api.Generator.Rest/Models/EnumMemberModel.cs
- Google.Api.Generator.Rest/Models/EnumModel.cs
- Google.Api.Generator.Rest/Models/MethodModel.cs
- Google.Api.Generator.Rest/Models/Naming.cs
- Google.Api.Generator.Rest/Models/PackageModel.cs
- Google.Api.Generator.Rest/Models/ParameterModel.cs
- Google.Api.Generator.Rest/Models/ResourceModel.cs
- Google.Api.Generator.Rest/Models/SchemaTypes.cs
- Google.Api.Generator.Utils/Formatting/WhitespaceFormatter.cs
- Google.Api.Generator.Utils/Roslyn/Annotations.cs
- Google.Api.Generator.Utils/Roslyn/RoslynBuilder.cs
- Google.Api.Generator.Utils/Roslyn/RoslynExtensions.cs
- Google.Api.Generator.Utils/Roslyn/XmlDoc.cs
- Google.Api.Generator.Utils/SourceFileContext.cs
- Google.Api.Generator.Utils/SystemExtensions.cs
- Google.Api.Generator.Utils/Typ.cs
There's one annoyance with the feature list formatting, but apart from that, Translate, WebFonts and Storage all generate in a whitespace-only-diff (and copyright) fashion. (For the C# code. We don't generate the project files yet.)
There may well be more differences to take account of when we generate more APIs...
Note that I'm assuming that https://github.com/googleapis/google-api-dotnet-client/pull/1651 will be merged - the final Storage sample update is based on that.
> Finish initial generator implementation

- Google.Api.Generator.Rest/Models/DataModel.cs
- Google.Api.Generator.Rest/Models/DataPropertyModel.cs
- Google.Api.Generator.Rest/Models/MethodModel.cs
- Google.Api.Generator.Rest/Models/Naming.cs
- Google.Api.Generator.Rest/Models/SchemaTypes.cs
- test-all-rest.sh
(No urgency to review this)
With these changes in, we generate the same code that the Python generator does.
Next step will be to refactor a bit, ideally to move everything around naming to one place, and reducing the number of public properties.
> Final changes to REST generator for parity

- rules_csharp_gapic/csharp_compiler.bzl
A lot of continuous integration builds (one or two per day) fail in Kokoro for no reason with this error:
```
failed: error executing command bazel-out/host/bin/external/com_google_protobuf/protoc --experimental_allow_proto3_optional '--plugin=protoc-gen-gapic=bazel-out/host/bin/external/gapic_generator_csharp/rules_csharp_gapic/run.sh' ... (remaining 17 argument(s) skipped)
Use --sandbox_debug to see verbose messages from the sandbox
Failed to create CoreCLR, HRESULT: 0x80004005
--gapic_out: protoc-gen-gapic: Plugin failed with status code 137.
```
The latest example of this failure can be seen in Sponge with ID 4a0cfd5f-e352-4b26-94a6-bf56052d59aa. They always pass if I restart the build.
Until the root cause is found (if it's possible to find the root cause at all :) ), let's try this …
> fix: rerun dotnet compiler if the first invocation fails

- bazel_example/WORKSPACE.bazel
- rules_csharp_gapic/csharp_compiler.bzl
- adds a missing backslash so that the env vars are no longer missing
- comments and formatting
> [fix] Fixes a backslash that got lost in d400f33bf904ea387819f783b8907404727bec01

- Google.Api.Generator.Rest/CodeGenerator.cs
- Google.Api.Generator.Rest/Models/MethodModel.cs
This will allow users to subscribe to progress (and make other
configuration changes) when performing ranged downloads.
Tested by:
- Regenerating all APIs in google-api-dotnet-client (succeeds)
- Rebuilding them all (succeeds)
- Checking the changes (all MediaDownloader-related)
- Building a local Storage package
- Using the ProgressChanged event handler as expected:
```csharp
var obj = client.Objects.Get(bucketName, objectName);
obj.MediaDownloader.ProgressChanged += MediaDownloader_ProgressChanged;
obj.MediaDownloader.ChunkSize = 5000;
obj.DownloadRange(new MemoryStream(), new System.Net.Http.Headers.RangeHeaderValue(100, 50_000_000));
```
This will address https://github.com/googleapis/google-api-dotnet-client/issues/1784
Strictly speaking it's a breaking change in that if someone were …
> (REST) Make DownloadRange use the MediaDownloader

- Google.Api.Generator.Rest/Models/PackageModel.cs
The NuGetIcon.png file already exists in google-api-dotnet-client.
> (REST) Improvements to generated project files

- Google.Api.Generator.Rest.Tests/PackageEnumStorageTest.cs
- Google.Api.Generator.Rest.Tests/TestResources.cs
- Google.Api.Generator.Rest/CodeGenerator.cs
- Google.Api.Generator.Rest/Models/EnumMemberModel.cs
- Google.Api.Generator.Rest/Models/EnumModel.cs
- Google.Api.Generator.Rest/Models/PackageModel.cs
- Google.Api.Generator.Rest/Models/ParameterModel.cs
- Google.Api.Generator.Rest/PackageEnumStorage.cs
- Google.Api.Generator.Rest/Program.cs
This prevents enum value reorderings in the Discovery doc from being breaking changes
> REST: Persist enum values in a JSON file

- Google.Api.Generator.Tests/ProtoTests/Paginated/Testing.Paginated.Snippets/PaginatedClientSnippets.g.cs
- Google.Api.Generator.Tests/ProtoTests/Paginated/Testing.Paginated.StandaloneSnippets/PaginatedClient.ResourcedMethod1AsyncSnippet.g.cs
- Google.Api.Generator.Tests/ProtoTests/Paginated/Testing.Paginated.StandaloneSnippets/PaginatedClient.ResourcedMethod1ResourceNamesAsyncSnippet.g.cs
- Google.Api.Generator.Tests/ProtoTests/Paginated/Testing.Paginated.StandaloneSnippets/PaginatedClient.ResourcedMethod2AsyncSnippet.g.cs
- Google.Api.Generator.Tests/ProtoTests/Paginated/Testing.Paginated.StandaloneSnippets/PaginatedClient.ResourcedMethod2ResourceNamesAsyncSnippet.g.cs
- Google.Api.Generator.Tests/ProtoTests/Paginated/Testing.Paginated.StandaloneSnippets/PaginatedClient.ResourcedMethodRequestObjectAsyncSnippet.g.cs
- Google.Api.Generator.Tests/ProtoTests/Paginated/Testing.Paginated.StandaloneSnippets/PaginatedClient.SignatureMethod1AsyncSnippet.g.cs
- Google.Api.Generator.Tests/ProtoTests/Paginated/Testing.Paginated.StandaloneSnippets/PaginatedClient.SignatureMethod2AsyncSnippet.g.cs
- Google.Api.Generator.Tests/ProtoTests/Paginated/Testing.Paginated.StandaloneSnippets/PaginatedClient.SignatureMethod2RequestObjectAsyncSnippet.g.cs
- Google.Api.Generator.Tests/ProtoTests/Paginated/Testing.Paginated.StandaloneSnippets/PaginatedClient.SignatureMethod3AsyncSnippet.g.cs
- Google.Api.Generator.Tests/ProtoTests/Paginated/Testing.Paginated.StandaloneSnippets/PaginatedClient.SignatureMethodRequestObjectAsyncSnippet.g.cs
- Google.Api.Generator/Generation/SnippetCodeGenerator.cs
This is ready for review, but it should be merged once the changes that this introduces in library generated code are in another PR in [googleapis/google-cloud-dotnet](https://github.com/googleapis/google-cloud-dotnet). I'm generating that PR just now.
> fix: Fixes the XML doc for paginated async snippets.

- Google.Api.Generator/CodeGenerator.cs
(Example: Google.Cloud.OsLogin.Common, where we just generate resources names.)
Ideally we'd actually delete any existing metadata file, but we don't have a way of expressing that - and it's very unlikely to happen.
> fix: Don't generate metadata when there are no services

- Google.Api.Generator.Tests/ProtoTests/GrpcServiceConfig/gapic_metadata.json
- Google.Api.Generator/Generation/MetadataGenerator.cs
(It would be nice if `MapField` contains an `Add` overload accepting an
`IEnumerable<TKey, TValue>`, but it doesn't at the moment. Using
SortedDictionary is a fairly simple alternative though.)
> fix: Make metadata generation order stable

- Google.Api.Generator.Rest/Models/EnumModel.cs
- Google.Api.Generator.Rest/Models/Naming.cs
- Google.Api.Generator.Rest/Models/SchemaTypes.cs
Found when generating https://admin.googleapis.com/$discovery/rest?version=directory_v1, which contains an enum named `event`.
> fix(REST): Type and property declaration for keyword named enums didn't match.

- Google.Api.Generator/Generation/SnippetCodeGenerator.cs
(No test as it would take massively longer to add a test than to
just check. The real test is that the API that is currently broken
is fixed by this change.)
> Disable deprecation warnings in snippets calling PollOnce for deprecated LROs

- bazel_example/BUILD.bazel
- bazel_example/WORKSPACE.bazel
- repositories.bzl
- rules_csharp_gapic/csharp_gapic.bzl
- rules_csharp_gapic/csharp_gapic_pkg.bzl
This is needed for the preliminary removal of the monolith rules from `googleapis`' `switched_rules_by_language`.
Confirming that `bazel_example` builds with this PR.
> fix(bazel): Remove monolith Bazel rule deps [csharp]

- repositories.bzl
Context: Cleaning up the removal of monolith Bazel deps from microgenerators, for the monolith's deprecation. Similar PRs in other microgenerators:
- [Java](https://github.com/googleapis/gapic-generator-java/pull/778)
- [Ruby](https://github.com/googleapis/gapic-generator-ruby/pull/614)
- [PHP](https://github.com/googleapis/gapic-generator-php/pull/311)
> fix(bazel): Eradicate monolith Bazel deps from C# µgen repo

- Google.Api.Generator.Tests/ProtoTests/Basic/Testing.Basic.Snippets/Testing.Basic.Snippets.csproj
- Google.Api.Generator.Tests/ProtoTests/Basic/Testing.Basic.StandaloneSnippets/Testing.Basic.StandaloneSnippets.csproj
- Google.Api.Generator.Tests/ProtoTests/Basic/Testing.Basic.Tests/Testing.Basic.Tests.csproj
- Google.Api.Generator.Tests/ProtoTests/Basic/Testing.Basic/Testing.Basic.csproj
- Google.Api.Generator.Tests/ProtoTests/Lro/Testing.Lro.Snippets/Testing.Lro.Snippets.csproj
- Google.Api.Generator.Tests/ProtoTests/Lro/Testing.Lro.StandaloneSnippets/Testing.Lro.StandaloneSnippets.csproj
- Google.Api.Generator.Tests/ProtoTests/Lro/Testing.Lro/Testing.Lro.csproj
- Google.Api.Generator/Generation/CsProjGenerator.cs
- Adds a reference to Microsoft.NETFramework.ReferenceAssemblies to allow the full package to be built anywhere
- Removes conditional framework targeting
- Updated Grpc.Core and GAX references
- Removes Protobuf reference which is now redundant
- Adds System.Linq.Async reference for snippets (as otherwise the code won't build)
(Most of this is changes to golden test files.)
> feat: Update project file package references

- Google.Api.Generator/Generation/MethodDetails.cs
- Google.Api.Generator/Generation/ServiceMethodGenerator.cs
In XML docs, cref attributes can specify open generic types, but not
constructed ones... which means we can't just use the paginated
resource type directly in all cases.
This is a potentially more general problem, but the fact that it
hasn't bitten us elsewhere is encouraging - if it strikes anywhere
else, we'll know because the generated code won't compile cleanly.
> fix: Generate appropriate XML docs for generic paginated resources

- Google.Api.Generator.Rest.Tests/Google.Api.Generator.Rest.Tests.csproj
- Google.Api.Generator.Rest/Google.Api.Generator.Rest.csproj
- Google.Api.Generator.Tests/Google.Api.Generator.Tests.csproj
- Google.Api.Generator.Utils/Google.Api.Generator.Utils.csproj
- Google.Api.Generator/Google.Api.Generator.csproj
This will avoid a huge slew of PRs when we first add Renovate support
> Update all dependencies prior to adding Renovate

- Google.Api.Generator.Tests/ProtoTests/Basic/Testing.Basic.Snippets/Testing.Basic.Snippets.csproj
- Google.Api.Generator.Tests/ProtoTests/Basic/Testing.Basic.StandaloneSnippets/Testing.Basic.StandaloneSnippets.csproj
- Google.Api.Generator.Tests/ProtoTests/Basic/Testing.Basic.Tests/Testing.Basic.Tests.csproj
- Google.Api.Generator.Tests/ProtoTests/Basic/Testing.Basic/Testing.Basic.csproj
- Google.Api.Generator.Tests/ProtoTests/Lro/Testing.Lro.Snippets/Testing.Lro.Snippets.csproj
- Google.Api.Generator.Tests/ProtoTests/Lro/Testing.Lro.StandaloneSnippets/Testing.Lro.StandaloneSnippets.csproj
- Google.Api.Generator.Tests/ProtoTests/Lro/Testing.Lro/Testing.Lro.csproj
- Google.Api.Generator/Generation/CsProjGenerator.cs
(This should cover everything Renovate was worrying about.)
Note: I've removed `<DotNetCliToolReference Include="dotnet-xunit" Version="2.3.1" />` because I believe it's now effectively obsolete.
> Update dependencies in generated project files

- Google.Api.Generator/Google.Api.Generator.csproj
It's unclear exactly why this is required, but it may well be due to
a separate recent dependency update. With this in place, it's fine.
> chore: Add System.Collections.Immutable dependency

- Google.Api.Generator/CodeGenerator.cs
- Google.Api.Generator/ProtoUtils/ProtoCatalog.cs
- Google.Api.Generator/ProtoUtils/ResourceDetails.cs
Before this commit, generation fails if any resource name field is
loaded without the resource definition being present. That's only
actually a problem if the field is used for generation - otherwise,
it's fine.
This commit fixes Google.Cloud.Asset.V1 to avoid an
otherwise-unnecessary import being required.
Once this has been submitted, we can create a release which will fix the Kokoro builds for googleapis/googleapis, and we can remove the workaround in google-cloud-dotnet.
> fix: Fix Asset generation which otherwise fails due to unknown resources

- Google.Api.Generator/Generation/MethodDetails.cs
BigQuery libraries do have generation Bazel rules, even though the published library is a handwritten veneer.
Turns out those libraries also have paginated methods with `max_results` and a type google.protobuf.UInt32Value and our new pagination detection falsely identifies those as errors.
> fix: carve a pagination detection exception for bigquery

- repositories.bzl
- rules_csharp_gapic/csharp_gapic.bzl
bringing our local grpc and proto rules (used by bazel_example) to a better state:
(1) `csharp_proto` and `csharp_grpc` rules are now just aliases to the rules from rules_gapic
(2) updated rules_gapic to the latest version
With this bazel_example now generates `Grpc.g.cs` files
> feat [bazel]: update and redirect proto and grpc rules

- Google.Api.Generator/Generation/MethodDetails.cs
This is a fix on the recent BigQuery pagination fix, which
unfortunately broke Compute.
> fix: Conditionalize access to the MessageType property

- Google.Api.Generator.Tests/ProtoTests/GrpcServiceConfig/Testing.GrpcServiceConfig/GrpcServiceConfigClient.g.cs
- Google.Api.Generator.Utils/Roslyn/XmlDoc.cs
- Google.Api.Generator/Generation/ServiceSettingsCodeGenerator.cs
It's not *completely* clear to me that we want to do this, but I suspect we do. (I'm finding out what other languages do.)
See below for an example of the result of this applied to `Google.Cloud.Vision.V1.ProductServiceSettings`:
> feat: Include status codes that will be retried within documentation

- Google.Api.Generator.Tests/ProtoTest.cs
- Google.Api.Generator/CodeGenerator.cs
- Google.Api.Generator/Program.cs
Initially I had expected to only remove the command-line option, but
keep the rest of the code - but it now feels cleaner to get rid of
it all in one go. I suspect if we left the conditionality in, we'd
never actually remove it.
> feat: Make gapic_metadata.json unconditional

- Google.Api.Generator.Rest.Tests/GoldenTestData/Google.Apis.ManufacturerCenter.v1/Google.Apis.ManufacturerCenter.v1.cs
- Google.Api.Generator.Rest.Tests/GoldenTestData/Google.Apis.ManufacturerCenter.v1/Google.Apis.ManufacturerCenter.v1.csproj
- Google.Api.Generator.Rest.Tests/GoldenTestData/Google.Apis.Storage.v1/Google.Apis.Storage.v1.cs
- Google.Api.Generator.Rest.Tests/GoldenTestData/Google.Apis.Storage.v1/Google.Apis.Storage.v1.csproj
- Google.Api.Generator.Rest.Tests/GoldenTestData/Google.Apis.Translate.v2/Google.Apis.Translate.v2.cs
- Google.Api.Generator.Rest.Tests/GoldenTestData/Google.Apis.Translate.v2/Google.Apis.Translate.v2.csproj
- Google.Api.Generator.Rest.Tests/GoldenTestData/Google.Apis.Webfonts.v1/Google.Apis.Webfonts.v1.cs
- Google.Api.Generator.Rest.Tests/GoldenTestData/Google.Apis.Webfonts.v1/Google.Apis.Webfonts.v1.csproj
Ideally we shouldn't need to do this every year, but let's unblock
other PRs for now...
> chore: Update expected data in tests to specify 2022

- Google.Api.Generator.Tests/Invoker.cs
- Google.Api.Generator.Tests/ProtoTest.cs
This makes it easier to perform fuller diffs, and to bootstrap new
tests. Files should still be reviewed carefully, of course.
cc @viacheslav-rostovtsev
> tests: write generated output to temporary directory

- Google.Api.Generator.Tests/Invoker.cs
We've occasionally seen CI failures like this:
>  Error Message:
>   System.InvalidOperationException : Collection was modified; enumeration operation may not execute.
I believe this is *just* because of a race condition between the
output being modified and the assertion.
Fixes #292
> chore: Fix occasional CI issue

- Google.Api.Generator.Tests/ProtoTest.cs
- Google.Api.Generator.Tests/ProtoTests/Mixins/Mixins.proto
- Google.Api.Generator.Tests/ProtoTests/Mixins/Mixins.yaml
- Google.Api.Generator.Tests/ProtoTests/Mixins/Testing.Mixins.Tests/MixinServiceClientTest.g.cs
- Google.Api.Generator.Tests/ProtoTests/Mixins/Testing.Mixins.Tests/Testing.Mixins.Tests.csproj
- Google.Api.Generator.Tests/ProtoTests/Mixins/Testing.Mixins/MixinFakes.cs
- Google.Api.Generator.Tests/ProtoTests/Mixins/Testing.Mixins/MixinServiceClient.g.cs
- Google.Api.Generator.Tests/ProtoTests/Mixins/Testing.Mixins/Testing.Mixins.csproj
- Google.Api.Generator.Tests/ProtoTests/Mixins/gapic_metadata.json
- Google.Api.Generator/CodeGenerator.cs
- Google.Api.Generator/Generation/CsProjGenerator.cs
- Google.Api.Generator/Generation/LroAdaptationGenerator.cs
- Google.Api.Generator/Generation/MetadataGenerator.cs
- Google.Api.Generator/Generation/ServiceAbstractClientClassCodeGenerator.cs
- Google.Api.Generator/Generation/ServiceCodeGenerator.cs
- Google.Api.Generator/Generation/ServiceDetails.cs
- Google.Api.Generator/Generation/ServiceImplClientClassGenerator.cs
- Google.Api.Generator/Generation/ServiceSettingsCodeGenerator.cs
- Google.Api.Generator/Generation/UnitTestCodeGeneration.cs
- Google.Api.Generator/Google.Api.Generator.csproj
- Google.Api.Generator/Program.cs
This won't build on CI as Google.Cloud.Location isn't released yet.
Various things still to do, mostly:
- Check whether routing header customization is an issue
- Generate proper XML docs instead of FIXME
- Work out whether the default mixin settings are appropriate
However, the result of generation does genuinely work:
https://github.com/googleapis/google-cloud-dotnet/pull/7426
(I've just tested listing locations, but that worked first time.)
> Implement mixin generation 

- Google.Api.Generator/Generation/ServiceDetails.cs
For example, LocationsClient shouldn't have a LocationsClient property
Fixes #438
(No extra tests for this, but local generation works now and didn't before.)
> fix: Don't use mixins in the same package that generates them

- bazel_example/WORKSPACE.bazel
old version throws an error with Bazel 5
> chore: update grpc version in bazel_example

- Google.Api.Generator/Generation/UnitTestCodeGeneration.cs
- Google.Api.Generator/ProtoUtils/ProtoExtensions.cs
- Fix one missing piece of decorating a property initializer with
deprecation suppression
- Change deprecation detection for fields to match protoc: if the
field isn't deprecated, but the parent message is, it's still
marked as being obsolete
> fix: Better deprecation handling

- Google.Api.Generator/Program.cs
This has always passed in CI and on some developer machines, but not
on all. I don't understand why the behavior was inconsistent, but
it's easy enough to address to make it pass regardless of the
precise nature of the failure.
> fix: Address BadCmdLineInvocation failing oddly

- Google.Api.Generator/Generation/SnippetCodeGenerator.cs
I ran the generator locally and most (all?) libraries with multiple clients are affected.
> feat: Stabilize snippet metadata file by sorting on service name.

- Google.Api.Generator.Tests/ProtoTest.cs
- Google.Api.Generator.Tests/ProtoTests/Showcase/Google.Showcase.V1Beta1/ComplianceClient.g.cs
- Google.Api.Generator.Tests/ProtoTests/Showcase/Google.Showcase.V1Beta1/EchoClient.g.cs
- Google.Api.Generator.Tests/ProtoTests/Showcase/Google.Showcase.V1Beta1/IdentityClient.g.cs
- Google.Api.Generator.Tests/ProtoTests/Showcase/Google.Showcase.V1Beta1/MessagingClient.g.cs
- Google.Api.Generator.Tests/ProtoTests/Showcase/Google.Showcase.V1Beta1/SequenceServiceClient.g.cs
- Google.Api.Generator.Tests/ProtoTests/Showcase/Google.Showcase.V1Beta1/TestingClient.g.cs
- Google.Api.Generator/CodeGenerator.cs
- Google.Api.Generator/Generation/LroAdaptationGenerator.cs
- Google.Api.Generator/Generation/ServiceAbstractClientClassCodeGenerator.cs
- Google.Api.Generator/Generation/ServiceDetails.cs
- Google.Api.Generator/Program.cs
This will allow generation to specify when we should allow gRPC/REST/both transports
Note that this is "transport" for consistency with other languages, despite effectively being plural.
> feat: Support a "transport" option for generation

- Google.Api.Generator/Program.cs
(Corresponding documentation change will be needed in google-cloud-dotnet)
> fix: Split transports on "+" instead of ";"

- Google.Api.Generator.Tests/ProtoTest.cs
- Google.Api.Generator.Tests/ProtoTests/Showcase/Google.Showcase.V1Beta1/PackageApiMetadata.g.cs
- Google.Api.Generator/CodeGenerator.cs
- Google.Api.Generator/Generation/PackageApiMetadataGenerator.cs
- Google.Api.Generator/Google.Api.Generator.csproj
- Google.Api.Generator/Program.cs
- rules_csharp_gapic/csharp_gapic.bzl
Note that this should not be *used* until GAX 4.1.0 is released.
(But it would be fine to be present and unused.)
> feat: Generator support for REST numeric enums

- Google.Api.Generator.Rest.Tests/Google.Api.Generator.Rest.Tests.csproj
- Google.Api.Generator.Tests/Google.Api.Generator.Tests.csproj
- Google.Api.Generator.Tests/ProtoTests/Basic.v1/Testing.Basic.V1.Tests/Testing.Basic.V1.Tests.csproj
- Google.Api.Generator.Tests/ProtoTests/Mixins/Testing.Mixins.Tests/Testing.Mixins.Tests.csproj
- Google.Api.Generator/Generation/CsProjGenerator.cs
In both generator and generated code.
(Note this does not affect google-cloud-dotnet as we generate out own projects there).
> tests: Updates Microsoft.Net.Test.Sdk dependencies from 17.2.0 => 17.3.0

- rules_csharp_gapic/csharp_compiler.bzl
- rules_csharp_gapic/csharp_compiler_repo.bzl
After the recent generator update, the builds started failing locally (while still working in Docker). Adding this environment variable fixes the problem, but please feel free to suggest a better solution if it exists :)
> fix: set DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1

- Generator.sln
- Google.Api.Generator.IntegrationTests/ComplianceRestTest.cs
- Google.Api.Generator.IntegrationTests/EchoTest.cs
- Google.Api.Generator.IntegrationTests/Google.Api.Generator.IntegrationTests.csproj
- Google.Api.Generator.IntegrationTests/ShowcaseTestBase.cs
- Google.Api.Generator.IntegrationTests/TestResources.cs
- Google.Api.Generator.IntegrationTests/compliance_suite.json
This is primarily aimed at the data-driven REST compliance tests, but starts building out the Echo tests too, including showing how an abstract test base class can be used to collect common gRPC+REST tests, with concrete subclasses inheriting those tests and adding transport-specific tests.
These tests will not run in GitHub actions, although it's always safe to run the tests - they will all be skipped unless the SHOWCASE_ENDPOINT environment variable is set (typically to http://localhost:7469). In future, we'll add nightly integration tests which stand up a local Showcase server before executing the tests.
> chore: First pass at Showcase integration tests

- Google.Api.Generator.Tests/ProtoTest.cs
- Google.Api.Generator.Tests/ProtoTests/Showcase/Google.Showcase.V1Beta1/ComplianceClient.g.cs
- Google.Api.Generator.Tests/ProtoTests/Showcase/Google.Showcase.V1Beta1/EchoClient.g.cs
- Google.Api.Generator.Tests/ProtoTests/Showcase/Google.Showcase.V1Beta1/Google.Showcase.V1Beta1.csproj
- Google.Api.Generator.Tests/ProtoTests/Showcase/Google.Showcase.V1Beta1/IdentityClient.g.cs
- Google.Api.Generator.Tests/ProtoTests/Showcase/Google.Showcase.V1Beta1/MessagingClient.g.cs
- Google.Api.Generator.Tests/ProtoTests/Showcase/Google.Showcase.V1Beta1/PackageApiMetadata.g.cs
- Google.Api.Generator.Tests/ProtoTests/Showcase/Google.Showcase.V1Beta1/SequenceServiceClient.g.cs
- Google.Api.Generator.Tests/ProtoTests/Showcase/Google.Showcase.V1Beta1/ServiceCollectionExtensions.g.cs
- Google.Api.Generator.Tests/ProtoTests/Showcase/Google.Showcase.V1Beta1/TestingClient.g.cs
- Google.Api.Generator.Tests/ProtoTests/Showcase/google/showcase/v1beta1/showcase_v1beta1.yaml
- Google.Api.Generator.Utils/Formatting/WhitespaceFormatter.cs
- Google.Api.Generator.Utils/Roslyn/RoslynExtensions.cs
- Google.Api.Generator/CodeGenerator.cs
- Google.Api.Generator/Generation/PackageApiMetadataGenerator.cs
- Google.Api.Generator/Google.Api.Generator.csproj
This requires two overall changes, both to PackageApiMetadata
- Include mix-in file descriptors in the list of descriptors for RestGrpcAdapter to use
- Expose HttpRule overrides from the service config (for mix-ins)
The latter requires https://github.com/googleapis/gax-dotnet/pull/616 to be merged, released, and then the project file updated (hence why this PR fails to build right now).
> feat: Handle REGAPIC mix-ins

- Google.Api.Generator.Rest/Models/MethodModel.cs
And assume responses are of type string, which is the same assumption made when the response is not specified at all.
> feat(Rest): Allow responses to be specified without a ref property.

- Google.Api.Generator.Rest.Tests/GoldenTestData/Google.Apis.ManufacturerCenter.v1/Google.Apis.ManufacturerCenter.v1.csproj
- Google.Api.Generator.Rest.Tests/GoldenTestData/Google.Apis.Storage.v1/Google.Apis.Storage.v1.csproj
- Google.Api.Generator.Rest.Tests/GoldenTestData/Google.Apis.Translate.v2/Google.Apis.Translate.v2.csproj
- Google.Api.Generator.Rest.Tests/GoldenTestData/Google.Apis.Webfonts.v1/Google.Apis.Webfonts.v1.csproj
- Google.Api.Generator.Rest/Models/PackageModel.cs
We still include the license file within the package, so we continue to meet all obligations, but this is easier for customers to validate.
(Non-urgent to review.)
> chore: Update packaging to use PackageLicenseExpression

- Google.Api.Generator.Tests/ProtoTests/PublishingSettings/ServiceConfig.yaml
- Google.Api.Generator/CodeGenerator.cs
The "version" is actually the fully-qualified proto package... which we happen to already have to hand.
(This isn't urgent - please wait until you're back!)
> fix: Filter which publication.library_settings we use by version

- Google.Api.Generator.Tests/ProtoTests/Showcase/Google.Showcase.V1Beta1/Google.Showcase.V1Beta1.csproj
- Google.Api.Generator/CodeGenerator.cs
- Google.Api.Generator/Generation/CsProjGenerator.cs
- Google.Api.Generator/Generation/ServiceDetails.cs
If we see that the NuGet package containing a mixin is required, even if we're not generating it as as mixin, include the package reference.
> feat: Generate dependencies for known packages

- rules_csharp_gapic/csharp_compiler_repo.bzl
The 6.0.408 SDK appears to have issues with our use of Docker in Bazel Bot. We'll temporarily downgrade (and release) just to get the pipeline working again, then work on a fix so that we can get back to the latest SDK. (Sticking at 6.0.402 permanently is not an option.)
> chore: Downgrade .NET SDK to 6.0.402, just for Bazel

- Google.Api.Generator.Rest.Tests/GeneratedCodeTest.cs
- Google.Api.Generator.Rest.Tests/GoldenTestData/Google.Apis.ManufacturerCenter.v1/Google.Apis.ManufacturerCenter.v1.cs
- Google.Api.Generator.Rest/Google.Api.Generator.Rest.csproj
- Google.Api.Generator.Rest/Models/DataPropertyModel.cs
We keep separate string and object representations for the sake of compatibility.
> feat: Generate Raw and DateTimeOffset properties for google-datetime properties

- Google.Api.Generator/CodeGenerator.cs
- Google.Api.Generator/Google.Api.Generator.csproj
These are left-over from when we generated unit tests.
> chore: Remove unnecessary dependencies.

- Google.Api.Generator.Rest.Tests/TestResources.cs
- Google.Api.Generator.Rest/Models/Features.cs
These haven't been used since #465 removed support for net40 and PCLs.
> chore: Remove legacy features configuration in REST generator configuration

- Google.Api.Generator.Rest/Google.Api.Generator.Rest.csproj
I suspect this was introduced at some point where it wasn't the default for the Discovery dependency - but it makes updating that dependency harder.
> chore: Remove redundant package reference

- Google.Api.Generator.Rest.Tests/GoldenTestData/Google.Apis.Contentwarehouse.v1/Google.Apis.Contentwarehouse.v1.csproj
- Google.Api.Generator.Rest.Tests/GoldenUnitTest.cs
- Google.Api.Generator.Rest/Models/DataPropertyModel.cs
Unblocks releasing Google.Apis.Contentwarehouse.v1
@jskeet as usual, a commit at a time so that generation changes are clear. I'll probably rebase into a single commit before merging though, the first commit won't even build.
> fix: Support REST responses with their own ETag field.

- Google.Api.Generator/Generation/PackageApiMetadataGenerator.cs
- Google.Api.Generator/Google.Api.Generator.csproj
This requires a tweak to the PackageApiMetadataGenerator, as an unqualified reference to PolicyReflection now resolves to Google.Api.PolicyReflection instead of Google.Cloud.Iam.V1.PolicyReflection. This won't affect users - it's only because our code is in a *namespace* starting with Google.Api, which takes priority over using directives.
> chore: Update Google.Api.CommonProtos to version 2.11.0

- Google.Api.Generator.Rest/Google.Api.Generator.Rest.csproj
At this point, we don't need the Google.Apis 1.64.0-alpha01 reference any more, as we get 1.64.0 transitively.
> chore: Update Discovery reference to 1.64.0

- Google.Api.Generator.Utils/Formatting/WhitespaceFormatter.cs
- Google.Api.Generator.Utils/Google.Api.Generator.Utils.csproj
- Google.Api.Generator/Google.Api.Generator.csproj
- We don't need Microsoft.CodeAnalysis.CSharp in both Google.Api.Generator and Google.Api.Generator.Utils
- Now that .NET 8 is released, it's fine to update to 8.0 libraries for generation purposes (no customer dependencies)
- An implicit conversion in SyntaxList was removed in Roslyn, requiring updates in WhitespaceFormatter
> chore: Update Microsoft.CodeAnalysis.CSharp and System.Collections.Immutable

- Google.Api.Generator.Tests/ProtoTests/Basic.v1/Testing.Basic.V1/BasicClient.g.cs
- Google.Api.Generator.Tests/ProtoTests/Deprecated/Testing.Deprecated/DeprecatedClient.g.cs
- Google.Api.Generator.Tests/ProtoTests/Keywords/Testing.Keywords/KeywordsClient.g.cs
- Google.Api.Generator.Tests/ProtoTests/MethodSignatures/Testing.MethodSignatures/MethodSignaturesClient.g.cs
- Google.Api.Generator.Tests/ProtoTests/Mixins/Testing.Mixins/MixinServiceClient.g.cs
- Google.Api.Generator.Tests/ProtoTests/PublishingSettings/Testing.PublishingSettings/RenamedServiceNameClient.g.cs
- Google.Api.Generator.Tests/ProtoTests/PublishingSettings/Testing.PublishingSettings/ServiceWithHandwrittenSignaturesClient.g.cs
- Google.Api.Generator.Tests/ProtoTests/PublishingSettings/Testing.PublishingSettings/ServiceWithResourcesClient.g.cs
- Google.Api.Generator.Tests/ProtoTests/ResourceNames/Testing.ResourceNames/ResourceNamesClient.g.cs
- Google.Api.Generator.Tests/ProtoTests/Showcase/Google.Showcase.V1Beta1/ComplianceClient.g.cs
- Google.Api.Generator.Tests/ProtoTests/Showcase/Google.Showcase.V1Beta1/EchoClient.g.cs
- Google.Api.Generator.Tests/ProtoTests/Showcase/Google.Showcase.V1Beta1/IdentityClient.g.cs
- Google.Api.Generator.Tests/ProtoTests/Showcase/Google.Showcase.V1Beta1/MessagingClient.g.cs
- Google.Api.Generator.Tests/ProtoTests/Showcase/Google.Showcase.V1Beta1/SequenceServiceClient.g.cs
- Google.Api.Generator.Tests/ProtoTests/Showcase/Google.Showcase.V1Beta1/TestingClient.g.cs
- Google.Api.Generator/Generation/ServiceBuilderCodeGenerator.cs
This is part of API key support. It's not expected to build yet, as it'll need a new version of GAX (which hasn't been published yet).
> feat: Generate calls to GetEffectiveSettings in the client builder

- Google.Api.Generator.Rest.Tests/GoldenTestData/Google.Apis.Assuredworkloads.v1/Google.Apis.Assuredworkloads.v1.cs
- Google.Api.Generator.Rest.Tests/GoldenTestData/Google.Apis.Calendar.v3/Google.Apis.Calendar.v3.cs
- Google.Api.Generator.Rest.Tests/GoldenTestData/Google.Apis.CloudSupport.v2/Google.Apis.CloudSupport.v2.cs
- Google.Api.Generator.Rest.Tests/GoldenTestData/Google.Apis.DataprocMetastore.v1/Google.Apis.DataprocMetastore.v1.cs
- Google.Api.Generator.Rest.Tests/GoldenTestData/Google.Apis.ManufacturerCenter.v1/Google.Apis.ManufacturerCenter.v1.cs
- Google.Api.Generator.Rest.Tests/GoldenTestData/Google.Apis.Storage.v1/Google.Apis.Storage.v1.cs
- Google.Api.Generator.Rest.Tests/GoldenTestData/Google.Apis.Translate.v2/Google.Apis.Translate.v2.cs
- Google.Api.Generator.Rest.Tests/GoldenTestData/Google.Apis.Webfonts.v1/Google.Apis.Webfonts.v1.cs
- Google.Api.Generator.Rest.Tests/Google.Api.Generator.Rest.Tests.csproj
- Google.Api.Generator.Rest/Models/MethodModel.cs
- Google.Api.Generator.Rest/Models/PackageModel.cs
- Google.Api.Generator.Tests/Google.Api.Generator.Tests.csproj
- Google.Api.Generator.Tests/ProtoTests/Basic.v1/Testing.Basic.V1/Testing.Basic.V1.csproj
- Google.Api.Generator.Tests/ProtoTests/Lro/Testing.Lro/Testing.Lro.csproj
- Google.Api.Generator.Tests/ProtoTests/Mixins/Testing.Mixins/Testing.Mixins.csproj
- Google.Api.Generator.Tests/ProtoTests/Showcase/Google.Showcase.V1Beta1/Google.Showcase.V1Beta1.csproj
- Google.Api.Generator.Utils.Tests/Google.Api.Generator.Utils.Tests.csproj
- Google.Api.Generator.Utils/Google.Api.Generator.Utils.csproj
- Google.Api.Generator.Utils/Roslyn/RoslynBuilder.cs
- Google.Api.Generator/Generation/CsProjGenerator.cs
- Google.Api.Generator/Google.Api.Generator.csproj
This has a dependency on googleapis/google-api-dotnet-client#2675 because generated code uses the methods defined there. This PR's presubmits won't be green until we have merged and released googleapis/google-api-dotnet-client#2675.
> feat: Universe domain support for discovery based libraries.

- Google.Api.Generator/Generation/MethodDetails.cs
The hope is that this workaround is temporary, superceded by explicit configuration. But it should unblock Compute generation for now.
> fix: Fix DIREGAPIC generation for new Compute protos

- Google.Api.Generator.Testing/TextComparer.cs
This used to be useful, but now that we write out all the generated files anyway, diffing or copying those is a simpler way of examining the output.
> chore: Remove unneeded console output

- Google.Api.Generator.Utils/Google.Api.Generator.Utils.csproj
I'm hoping that once this is merged, if we retry #783 then it should only attempt to update dotnet-sdk and we'll be able to close it without it re-opening.
> build: Update Microsoft.Extensions.Logging.Abstractions dependency

- Google.Api.Generator.Utils/Logging.cs
When we're autoflushing, it shouldn't matter anyway.
Fixes b/333505021
> fix: Don't specify buffer size in logging

- Google.Api.Generator.Rest/Models/DataModel.cs
- Google.Api.Generator.Rest/Models/DataPropertyModel.cs
- Google.Api.Generator.Rest/Models/EnumMemberModel.cs
- Google.Api.Generator.Rest/Models/EnumModel.cs
- Google.Api.Generator.Rest/Models/MethodModel.cs
- Google.Api.Generator.Rest/Models/ParameterModel.cs
- Google.Api.Generator.Utils/Roslyn/RoslynExtensions.cs
- Google.Api.Generator.Utils/Roslyn/XmlDoc.cs
This allows us to avoid `if` statements where we may not have a summary. I believe this is only currently useful in the REST generator.
Fixes #706.
I'm currently regenerating everything in google-api-dotnet-client to validate that it's a no-op change.
> refactor: Add conditional ("Maybe") XML doc generation methods

- Google.Api.Generator/ProtoUtils/ResourceDetails.cs
For example, if an `Account` resource has `name` and `account_name` properties, we don't want to generate an `AccountName` property in GAPIC, as that collides with the one generated by protoc. Instead, we generate `NameAsAccountName`.
No tests for this edge case, but I've run the generator against the Merchant Accounts API (which flagged this up) and the result builds where it didn't before.
Fixes b/343924087
> fix: Disambiguate resource name collisions

- Google.Api.Generator/ProtoUtils/ResourceDetails.cs
Without knowing which resource definition is invalid, it's hard to find the offending bit of the proto file.
> chore: Provide better error messages for invalid resource definitions

- Directory.Packages.props
- Google.Api.Generator.Tests/ProtoTests/Basic.v1/Testing.Basic.V1/Testing.Basic.V1.csproj
- Google.Api.Generator.Tests/ProtoTests/Lro/Testing.Lro/Testing.Lro.csproj
- Google.Api.Generator.Tests/ProtoTests/Mixins/Testing.Mixins/Testing.Mixins.csproj
- Google.Api.Generator.Tests/ProtoTests/Showcase/Google.Showcase.V1Beta1/Google.Showcase.V1Beta1.csproj
- Google.Api.Generator/Generation/CsProjGenerator.cs
- Google.Api.Generator/Google.Api.Generator.csproj
The direct Google.Protobuf dependency is no longer needed as the one in GAX is the latest.
> chore: Update to latest GAX

- Google.Api.Generator/CodeGenerator.cs
- Google.Api.Generator/Generation/EnumStringGenerator.cs
This moves code from google-cloud-dotnet to the generator, removing the post-processing.
We can probably adopt this as-is for the moment (given that this is only for DIREGAPIC, and only Compute uses DIREGAPIC) but we should really have configuration within the service config publish settings to turn this feature on (and potentially configure the filename; that'll be easier to tell if we end up with more examples).
> feat: Generate enum strings for Compute

- rules_csharp_gapic/csharp_compiler.bzl
The first run of "dotnet" in any given location includes output of:
> An issue was encountered verifying workloads. For more information,
> run "dotnet workload update"
... which is unhelpful when stdout is being used by protoc.
The DOTNET_SKIP_WORKLOAD_INTEGRITY_CHECK environment variable skips this check.
> fix: avoid bazel rules failing due to unexpected dotnet output

- Google.Api.Generator.Rest/Google.Api.Generator.Rest.csproj
- Google.Api.Generator/Google.Api.Generator.csproj
Changes since 1.4.34:
- Fix use of .NET 8 in Bazel
> chore: Release GAPIC generator 1.4.35
