Google.Api.Generator.Tests/ProtoTest.cs
Google.Api.Generator.Tests/WhitespaceFormatterTest.cs
Google.Api.Generator/Formatting/WhitespaceFormatter.cs
Google.Api.Generator/Generation/ServiceSettingsCodeGenerator.cs
Google.Api.Generator/Generation/SourceFileContext.cs
Google.Api.Generator/RoslynUtils/RoslynBuilder.cs
Google.Api.Generator/RoslynUtils/RoslynConverters.cs
Google.Api.Generator/RoslynUtils/RoslynExtensions.cs
Google.Api.Generator/RoslynUtils/XmlDoc.cs
Google.Api.Generator/Utils/Typ.cs

Including extra code required to generate this method, and tests

Add first method to the Settings class

---

Google.Api.Generator.Tests/ProtoTest.cs
Google.Api.Generator/Generation/ServiceSettingsCodeGenerator.cs
Google.Api.Generator/Generation/SourceFileContext.cs
Google.Api.Generator/RoslynUtils/RoslynBuilder.cs
Google.Api.Generator/RoslynUtils/RoslynConverters.cs
Google.Api.Generator/RoslynUtils/RoslynExtensions.cs

Add code required to generate settings copy ctor

---

Google.Api.CommonProtosExtra/Google.Api.CommonProtosExtra.csproj
Google.Api.Generator.Tests/Google.Api.Generator.Tests.csproj
Google.Api.Generator.Tests/ProtoTest.cs
Google.Api.Generator.Tests/ProtoTests/Basic.proto
Google.Api.Generator.Tests/ProtoTests/BasicClient.cs
Google.Api.Generator.Tests/WhitespaceFormatterTest.cs
Google.Api.Generator/Formatting/WhitespaceFormatter.cs
Google.Api.Generator/Generation/MethodDetails.cs
Google.Api.Generator/Generation/ServiceSettingsCodeGenerator.cs
Google.Api.Generator/ProtoUtils/ProtoConsts.cs
Google.Api.Generator/RoslynUtils/Modifier.cs
Google.Api.Generator/RoslynUtils/RoslynBuilder.cs
Google.Api.Generator/RoslynUtils/RoslynConverters.cs
Google.Api.Generator/RoslynUtils/RoslynExtensions.cs
Google.Api.Generator/RoslynUtils/XmlDoc.cs

Retry has changed from the current config/generator. There are various ways we can mantain compatibility which we can discuss later.
Please excuse the crazy long lines, I'll get a line-length-formatter in soon ;)

Add retry settings

---

Google.Api.Generator.Tests/ProtoTests/BasicClient.cs
Google.Api.Generator.Tests/ProtoTests/BasicGrpcClientFake.cs
Google.Api.Generator.Tests/WhitespaceFormatterTest.cs
Google.Api.Generator/Formatting/WhitespaceFormatter.cs
Google.Api.Generator/Generation/ServiceAbstractClientClassCodeGenerator.cs
Google.Api.Generator/RoslynUtils/RoslynBuilder.cs
Google.Api.Generator/RoslynUtils/RoslynExtensions.cs
Google.Api.Generator/RoslynUtils/XmlDoc.cs

And more formatting
XMLDoc formatting is currently terrible. It'll be sorted out in a furture PR.

Add all "Create" methods to abstract client

---

Google.Api.Generator.Tests/Google.Api.Generator.Tests.csproj
Google.Api.Generator.Tests/ProtoTest.cs
Google.Api.Generator.Tests/ProtoTests/MethodSignatures/MethodSignatures.proto
Google.Api.Generator.Tests/ProtoTests/MethodSignatures/MethodSignaturesClient.cs
Google.Api.Generator.Tests/ProtoTests/MethodSignatures/MethodSignaturesFakes.cs
Google.Api.Generator.Tests/WhitespaceFormatterTest.cs
Google.Api.Generator/Formatting/WhitespaceFormatter.cs
Google.Api.Generator/Formatting/XmlDocSplitter.cs
Google.Api.Generator/Generation/MethodDetails.cs
Google.Api.Generator/Generation/ServiceMethodGenerator.Signatures.cs
Google.Api.Generator/Generation/ServiceMethodGenerator.cs
Google.Api.Generator/Generation/ServiceSettingsCodeGenerator.cs
Google.Api.Generator/Generation/SourceFileContext.cs
Google.Api.Generator/ProtoUtils/ProtoConsts.cs
Google.Api.Generator/ProtoUtils/ProtoExtensions.cs
Google.Api.Generator/RoslynUtils/ObjectInitExpr.cs
Google.Api.Generator/RoslynUtils/RoslynBuilder.cs
Google.Api.Generator/RoslynUtils/RoslynExtensions.cs
Google.Api.Generator/RoslynUtils/XmlDoc.cs
Google.Api.Generator/Utils/Typ.cs

Method Signatures within Paginated, LRO, etc... RPCs coming in a future PR

Method Signatures (flattening) of basic RPCs

---

Google.Api.Generator.Tests/Google.Api.Generator.Tests.csproj
Google.Api.Generator.Tests/ProtoTests/Basic/BasicClientSnippets.g.cs
Google.Api.Generator.Tests/ProtoTests/BasicBidiStreaming/BasicBidiStreamingClientSnippets.g.cs
Google.Api.Generator.Tests/ProtoTests/BasicLro/BasicLroClientSnippets.g.cs
Google.Api.Generator.Tests/ProtoTests/BasicPaginated/BasicPaginatedClientSnippets.g.cs
Google.Api.Generator.Tests/ProtoTests/BasicServerStreaming/BasicServerStreamingClientSnippets.g.cs
Google.Api.Generator.Tests/ProtoTests/Lro/LroClientSnippets.g.cs
Google.Api.Generator.Tests/ProtoTests/MethodSignatures/MethodSignaturesClientSnippets.g.cs
Google.Api.Generator.Tests/ProtoTests/Paginated/PaginatedClientSnippets.g.cs
Google.Api.Generator.Tests/ProtoTests/ResourceNames/ResourceNamesClientSnippets.g.cs
Google.Api.Generator.Tests/ProtoTests/ServerStreaming/ServerStreamingClientSnippets.g.cs
Google.Api.Generator/CodeGenerator.cs
Google.Api.Generator/Formatting/WhitespaceFormatter.cs
Google.Api.Generator/Generation/MethodDetails.cs
Google.Api.Generator/Generation/ServiceDetails.cs
Google.Api.Generator/Generation/SnippetCodeGenerator.cs
Google.Api.Generator/Generation/SourceFileContext.cs
Google.Api.Generator/RoslynUtils/RoslynConverters.cs

Only currently generates snippets for the request-object methods; and won't yet correctly generate suitable values for a request.

Start of snippet generation

---

Google.Api.Generator.Tests/ProtoTests/Snippets/Snippets.proto
Google.Api.Generator.Tests/ProtoTests/Snippets/SnippetsClientFakes.cs
Google.Api.Generator.Tests/ProtoTests/Snippets/SnippetsClientSnippets.g.cs
Google.Api.Generator/Generation/SourceFileContext.cs

Test snippet default values for messages.

---

Google.Api.Generator/Generation/SnippetCodeGenerator.cs

In preparation of snippet generation of method signatures.

Pure refactor of snippet generation

---

Google.Api.Generator.Tests/ProtoTests/Snippets/Snippets.proto
Google.Api.Generator.Tests/ProtoTests/Snippets/SnippetsClientFakes.cs
Google.Api.Generator.Tests/ProtoTests/Snippets/SnippetsClientSnippets.g.cs
Google.Api.Generator/Generation/SnippetCodeGenerator.cs

Normal methods only, LRO/Paginated/... coming soon

Snippets for signatures with resource-names

---

Google.Api.Generator.Tests/Google.Api.Generator.Tests.csproj
Google.Api.Generator.Tests/ProtoTest.cs
Google.Api.Generator.Tests/ProtoTests/Basic/Testing.Basic/BasicFakes.cs
Google.Api.Generator.Tests/ProtoTests/Basic/Testing.Basic/Testing.Basic.csproj
Google.Api.Generator.Tests/ProtoTests/BasicBidiStreaming/Testing.BasicBidiStreaming/Testing.BasicBidiStreaming.csproj
Google.Api.Generator.Tests/ProtoTests/BasicLro/Testing.BasicLro/Testing.BasicLro.csproj
Google.Api.Generator.Tests/ProtoTests/BasicPaginated/Testing.BasicPaginated/Testing.BasicPaginated.csproj
Google.Api.Generator.Tests/ProtoTests/BasicServerStreaming/Testing.BasicServerStreaming/Testing.BasicServerStreaming.csproj
Google.Api.Generator.Tests/ProtoTests/Lro/Testing.Lro/LroClient.cs
Google.Api.Generator.Tests/ProtoTests/Lro/Testing.Lro/LroFakes.cs
Google.Api.Generator.Tests/ProtoTests/Lro/Testing.Lro/Testing.Lro.csproj
Google.Api.Generator.Tests/ProtoTests/MethodSignatures/Testing.MethodSignatures/Testing.MethodSignatures.csproj
Google.Api.Generator.Tests/ProtoTests/Paginated/Testing.Paginated/Testing.Paginated.csproj
Google.Api.Generator.Tests/ProtoTests/ResourceNames/Testing.ResourceNames/Testing.ResourceNames.csproj
Google.Api.Generator.Tests/ProtoTests/ServerStreaming/Testing.ServerStreaming/Testing.ServerStreaming.csproj
Google.Api.Generator.Tests/ProtoTests/Snippets/Testing.Snippets/Testing.Snippets.csproj
Google.Api.Generator/CodeGenerator.cs
Google.Api.Generator/Generation/CsProjGenerator.cs

Plus 'build' test that confirms the generated project successfully builds.

csproj file generation in the client

---

Google.Api.Generator.Tests/Google.Api.Generator.Tests.csproj
Google.Api.Generator.Tests/ProtoTest.cs
Google.Api.Generator.Tests/ProtoTests/Basic/Testing.Basic.Snippets/Testing.Basic.Snippets.csproj
Google.Api.Generator.Tests/ProtoTests/Basic/Testing.Basic/Testing.Basic.csproj
Google.Api.Generator.Tests/ProtoTests/BasicBidiStreaming/Testing.BasicBidiStreaming.Snippets/Testing.BasicBidiStreaming.Snippets.csproj
Google.Api.Generator.Tests/ProtoTests/BasicLro/Testing.BasicLro.Snippets/Testing.BasicLro.Snippets.csproj
Google.Api.Generator.Tests/ProtoTests/BasicPaginated/Testing.BasicPaginated.Snippets/Testing.BasicPaginated.Snippets.csproj
Google.Api.Generator.Tests/ProtoTests/BasicServerStreaming/Testing.BasicServerStreaming.Snippets/Testing.BasicServerStreaming.Snippets.csproj
Google.Api.Generator.Tests/ProtoTests/Lro/Testing.Lro.Snippets/Testing.Lro.Snippets.csproj
Google.Api.Generator.Tests/ProtoTests/Lro/Testing.Lro/Testing.Lro.csproj
Google.Api.Generator.Tests/ProtoTests/MethodSignatures/Testing.MethodSignatures.Snippets/Testing.MethodSignatures.Snippets.csproj
Google.Api.Generator.Tests/ProtoTests/Paginated/Testing.Paginated.Snippets/Testing.Paginated.Snippets.csproj
Google.Api.Generator.Tests/ProtoTests/ResourceNames/Testing.ResourceNames.Snippets/Testing.ResourceNames.Snippets.csproj
Google.Api.Generator.Tests/ProtoTests/ServerStreaming/Testing.ServerStreaming.Snippets/Testing.ServerStreaming.Snippets.csproj
Google.Api.Generator.Tests/ProtoTests/Snippets/Testing.Snippets.Snippets/Testing.Snippets.Snippets.csproj
Google.Api.Generator/CodeGenerator.cs
Google.Api.Generator/Generation/CsProjGenerator.cs

Generate csproj files in snippets

---

Google.Api.Generator.Tests/ProtoTests/Paginated/Testing.Paginated.Snippets/PaginatedClientSnippets.g.cs
Google.Api.Generator.Tests/ProtoTests/Paginated/Testing.Paginated/PaginatedClient.cs
Google.Api.Generator.Tests/WhitespaceFormatterTest.cs
Google.Api.Generator/Formatting/WhitespaceFormatter.cs
Google.Api.Generator/Generation/MethodDetails.cs
Google.Api.Generator/Generation/ServiceMethodGenerator.cs
Google.Api.Generator/Generation/SnippetCodeGenerator.cs
Google.Api.Generator/RoslynUtils/RoslynBuilder.cs
Google.Api.Generator/RoslynUtils/RoslynConverters.cs

async and resource-names will come in a future PR.
Found a bug in paginated signature method generation; have added a TODO.

Snippets for sync paginated methods

---

Google.Api.Generator.Tests/ProtoTest.cs
Google.Api.Generator.Tests/ProtoTests/Paginated/Testing.Paginated.Snippets/PaginatedClientSnippets.g.cs
Google.Api.Generator.Tests/ProtoTests/Paginated/Testing.Paginated/PaginatedClient.cs
Google.Api.Generator.Tests/WhitespaceFormatterTest.cs
Google.Api.Generator/Formatting/WhitespaceFormatter.cs
Google.Api.Generator/Generation/SnippetCodeGenerator.cs
Google.Api.Generator/Generation/SourceFileContext.cs
Google.Api.Generator/RoslynUtils/RoslynBuilder.cs

Async snippets for paginated methods

---

Google.Api.Generator/Generation/ServiceMethodGenerator.cs

A previous PR implemented the code-gen and tests for the signature edge-case.

Remove completed TODO

---

Google.Api.Generator.Tests/Google.Api.Generator.Tests.csproj
Google.Api.Generator.Tests/ProtoTest.cs
Google.Api.Generator.Tests/ProtoTests/Basic/Testing.Basic.Tests/BasicClientTest.g.cs
Google.Api.Generator.Tests/ProtoTests/Basic/Testing.Basic/BasicFakes.cs
Google.Api.Generator.Tests/WhitespaceFormatterTest.cs
Google.Api.Generator/CodeGenerator.cs
Google.Api.Generator/Formatting/WhitespaceFormatter.cs
Google.Api.Generator/Generation/MethodDetails.cs
Google.Api.Generator/Generation/ServiceDetails.cs
Google.Api.Generator/Generation/SnippetCodeGenerator.cs
Google.Api.Generator/Generation/SourceFileContext.cs
Google.Api.Generator/Generation/UnitTestCodeGeneration.cs
Google.Api.Generator/Google.Api.Generator.csproj
Google.Api.Generator/RoslynUtils/RoslynExtensions.cs

Only generates sync request-method generation at the moment; and is not yet well-tested.

Start of unit test generation

---

Google.Api.Generator.Tests/ProtoTests/Snippets/Snippets.proto
Google.Api.Generator.Tests/ProtoTests/Snippets/SnippetsClientFakes.cs
Google.Api.Generator.Tests/ProtoTests/Snippets/Testing.Snippets.Snippets/SnippetsClientSnippets.g.cs
Google.Api.Generator/Generation/SnippetCodeGenerator.cs
Google.Api.Generator/Generation/SourceFileContext.cs
Google.Api.Generator/Utils/Typ.cs

Fix bug in snippet generation of signatures with repeated field

---

Google.Api.Generator.Tests/XmlDocSplitterTest.cs
Google.Api.Generator/Formatting/XmlDocSplitter.cs

And new test of xmldoc formatter

Remove whitespace from end of preformatted lines

---

Google.Api.Generator.Tests/ProtoTests/Lro/Testing.Lro/LroResourceNames.g.cs
Google.Api.Generator.Tests/ProtoTests/Paginated/Testing.Paginated/PaginatedResourceNames.g.cs
Google.Api.Generator.Tests/ProtoTests/ResourceNames/Testing.ResourceNames/ResourceNamesResourceNames.g.cs
Google.Api.Generator.Tests/ProtoTests/ServerStreaming/Testing.ServerStreaming/ServerStreamingResourceNames.g.cs
Google.Api.Generator.Tests/ProtoTests/UnitTests/Testing.UnitTests/UnitTestsResourceNames.g.cs
Google.Api.Generator/Generation/ResourceNamesGenerator.cs

Updates https://github.com/googleapis/google-cloud-dotnet/issues/2443

Add resource-name path formatting helpers

---

Google.Api.Generator/Generation/MethodDetails.cs
Google.Api.Generator/Generation/ServiceMethodGenerator.Signatures.cs

To conform to other property names.

Minor property rename

---

Google.Api.Generator.Tests/ProtoTests/ResourceNames/ResourceNames.proto
Google.Api.Generator.Tests/ProtoTests/ResourceNames/ResourceNamesFakes.cs
Google.Api.Generator.Tests/ProtoTests/ResourceNames/Testing.ResourceNames/ResourceNamesResourceNames.g.cs

Test for fully-qualified type access in proto message partial

---

Google.Api.Generator/ProtoUtils/ResourceDetails.cs

Improve error messages for resource name generation

---

Google.Api.Generator.Tests/ProtoTest.cs
Google.Api.Generator.Tests/ProtoTests/ResourceNames/ResourceNames.proto
Google.Api.Generator.Tests/ProtoTests/UnknownResource/Testing.UnknownResource/UnknownResourceResourceNames.g.cs
Google.Api.Generator.Tests/ProtoTests/UnknownResource/Testing.UnknownResource/UnknownResourcesClient.g.cs
Google.Api.Generator.Tests/ProtoTests/UnknownResource/UnknownResource.proto
Google.Api.Generator.Tests/ProtoTests/UnknownResource/UnknownResourceFakes.cs
Google.Api.Generator/ProtoUtils/ResourceDetails.cs

Support '*' as a resource ref

---

Google.Api.Generator.Tests/ProtoTests/Paginated/Paginated.proto
Google.Api.Generator.Tests/ProtoTests/Paginated/PaginatedFakes.cs
Google.Api.Generator.Tests/ProtoTests/Paginated/Testing.Paginated.Snippets/PaginatedClientSnippets.g.cs
Google.Api.Generator.Tests/ProtoTests/Paginated/Testing.Paginated/PaginatedClient.g.cs
Google.Api.Generator/Generation/SourceFileContext.cs

Fix bug in nested class handling when outside of a class

---

Google.Api.Generator.Tests/ProtoTests/MethodSignatures/MethodSignatures.proto
Google.Api.Generator.Tests/ProtoTests/MethodSignatures/MethodSignaturesFakes.cs
Google.Api.Generator.Tests/ProtoTests/MethodSignatures/Testing.MethodSignatures/MethodSignaturesClient.g.cs
Google.Api.Generator/Generation/MethodDetails.cs
Google.Api.Generator/Generation/ServiceMethodGenerator.Signatures.cs
Google.Api.Generator/Utils/Typ.cs

Support map fields in method signatures

---

Google.Api.Generator.Tests/ProtoTests/GrpcServiceConfig/GrpcServiceConfig.proto
Google.Api.Generator.Tests/ProtoTests/GrpcServiceConfig/Testing.GrpcServiceConfig/GrpcServiceConfigClient.g.cs
Google.Api.Generator/Generation/ServiceSettingsCodeGenerator.cs

Fix retry on streaming methods

---

Google.Api.Generator.Tests/ProtoTests/Snippets/Snippets.proto
Google.Api.Generator.Tests/ProtoTests/Snippets/SnippetsClientFakes.cs
Google.Api.Generator.Tests/ProtoTests/Snippets/Testing.Snippets.Snippets/SnippetsClientSnippets.g.cs
Google.Api.Generator/Generation/SnippetCodeGenerator.cs

Generate correct initializers for map parameters in snippets

---

NuGet.Config

I'm not sure how this got reset (in next-major-version) but this should fix it.

Fix NuGet.config

---

Google.Api.Generator.Tests/ProtoTests/ResourceNames/ResourceNames.proto
Google.Api.Generator.Tests/ProtoTests/ResourceNames/Testing.ResourceNames/ResourceNamesResourceNames.g.cs
Google.Api.Generator/Generation/ResourceNamesGenerator.cs
Google.Api.Generator/Utils/SystemExtensions.cs

Support const resource-name pattern

---

Google.Api.Generator.Tests/ProtoTest.cs
Google.Api.Generator.Tests/ProtoTests/ResourceNameSeparator/ManualTests.cs
Google.Api.Generator.Tests/ProtoTests/ResourceNameSeparator/ResourceNameSeparator.proto
Google.Api.Generator.Tests/ProtoTests/ResourceNameSeparator/ResourceNameSeparatorFakes.cs
Google.Api.Generator.Tests/ProtoTests/ResourceNameSeparator/Testing.ResourceNameSeparator/ResourceNameSeparatorClient.g.cs
Google.Api.Generator.Tests/ProtoTests/ResourceNameSeparator/Testing.ResourceNameSeparator/ResourceNameSeparatorResourceNames.g.cs
Google.Api.Generator.Tests/WhitespaceFormatterTest.cs
Google.Api.Generator/Formatting/WhitespaceFormatter.cs
Google.Api.Generator/Generation/ResourceNamesGenerator.cs
Google.Api.Generator/Generation/SnippetCodeGenerator.cs
Google.Api.Generator/ProtoUtils/ResourceDetails.cs
Google.Api.Generator/RoslynUtils/RoslynBuilder.cs
Google.Api.Generator/RoslynUtils/RoslynExtensions.cs
Google.Api.Generator/Utils/ResourcePattern.cs

Support multi-ID path-segments in resource names

---

Google.Api.Generator.Tests/ProtoTests/Keywords/Keywords.proto
Google.Api.Generator.Tests/ProtoTests/Keywords/KeywordsFakes.cs
Google.Api.Generator.Tests/ProtoTests/Keywords/Testing.Keywords.Snippets/KeywordsClientSnippets.g.cs
Google.Api.Generator.Tests/ProtoTests/Keywords/Testing.Keywords.Tests/KeywordsClientTest.g.cs
Google.Api.Generator.Tests/ProtoTests/Keywords/Testing.Keywords/KeywordsClient.g.cs
Google.Api.Generator/ProtoUtils/ProtoExtensions.cs

Use Types_ as the property name for a field called 'types'

---

Google.Api.Generator.Tests/ProtoTests/Basic/Basic.proto
Google.Api.Generator.Tests/ProtoTests/Basic/Testing.Basic/BasicClient.g.cs
Google.Api.Generator.Tests/ProtoTests/Deprecated/Testing.Deprecated/DeprecatedClient.g.cs
Google.Api.Generator.Tests/ProtoTests/Keywords/Testing.Keywords/KeywordsClient.g.cs
Google.Api.Generator.Tests/ProtoTests/UnitTests/Testing.UnitTests/UnitTestsClient.g.cs
Google.Api.Generator/Generation/ServiceAbstractClientClassCodeGenerator.cs
Google.Api.Generator/Generation/ServiceDetails.cs
Google.Api.Generator/Generation/ServiceImplClientClassGenerator.cs
Google.Api.Generator/RoslynUtils/XmlDoc.cs

Add a "remarks" section for client (abstract and impl) with comments from proto

---

Google.Api.Generator.Rest/Models/EnumMemberModel.cs
Google.Api.Generator.Rest/Models/EnumModel.cs
Google.Api.Generator.Rest/Models/PackageModel.cs
Google.Api.Generator.Rest/Models/ParameterModel.cs
Google.Api.Generator.Rest/Models/SchemaTypes.cs
Google.Api.Generator.Tests/WhitespaceFormatterTest.cs
Google.Api.Generator.Utils/Formatting/WhitespaceFormatter.cs
Google.Api.Generator.Utils/Roslyn/RoslynConverters.cs
Google.Api.Generator.Utils/Roslyn/RoslynExtensions.cs
Google.Api.Generator/Generation/UnitTestCodeGeneration.cs
test-rest.sh

Review one commit at a time. This is just fixing up the base request, really - although I expect a lot of it may be useful elsewhere later.

More REST generator changes

---

Google.Api.Generator.Rest/Models/MethodModel.cs
Google.Api.Generator.Rest/Models/ParameterModel.cs
Google.Api.Generator.Utils/Roslyn/XmlDoc.cs

The next step will be to generate the Data classes properly so we can access those for both the "body" parameter and the response type for request classes.

Add the remainder of the Request class generated for methods

---

Google.Api.Generator.Rest/CodeGenerator.cs
Google.Api.Generator.Rest/Models/DataModel.cs
Google.Api.Generator.Rest/Models/DataPropertyModel.cs
Google.Api.Generator.Rest/Models/MethodModel.cs
Google.Api.Generator.Rest/Models/PackageModel.cs
Google.Api.Generator.Rest/Models/ResourceModel.cs
Google.Api.Generator.Tests/ProtoTests/ChildResource/Testing.ChildResource/ChildResourceResourceNames.g.cs
Google.Api.Generator.Tests/ProtoTests/Keywords/Testing.Keywords/KeywordsResourceNames.g.cs
Google.Api.Generator.Tests/ProtoTests/Lro/Testing.Lro/LroResourceNames.g.cs
Google.Api.Generator.Tests/ProtoTests/OptionalFields/Testing.OptionalFields/OptionalFieldsResourceNames.g.cs
Google.Api.Generator.Tests/ProtoTests/Paginated/Testing.Paginated/PaginatedResourceNames.g.cs
Google.Api.Generator.Tests/ProtoTests/ResourceNameSeparator/Testing.ResourceNameSeparator/ResourceNameSeparatorResourceNames.g.cs
Google.Api.Generator.Tests/ProtoTests/ResourceNames/Testing.ResourceNames/ResourceNamesResourceNames.g.cs
Google.Api.Generator.Tests/ProtoTests/ServerStreaming/Testing.ServerStreaming/ServerStreamingResourceNames.g.cs
Google.Api.Generator.Tests/ProtoTests/Snippets/Testing.Snippets/SnippetsResourceNames.g.cs
Google.Api.Generator.Tests/ProtoTests/UnitTests/Testing.UnitTests/UnitTestsResourceNames.g.cs
Google.Api.Generator.Tests/WhitespaceFormatterTest.cs
Google.Api.Generator.Utils/Formatting/WhitespaceFormatter.cs

(Review one commit at a time, as normal.)

Next set of changes for the REST generator

---

Google.Api.Generator.Rest.Tests/GoldenTestData/Google.Apis.Storage.v1/Google.Apis.Storage.v1.cs
Google.Api.Generator.Rest.Tests/GoldenTestData/Google.Apis.Storage.v1/discovery.json
Google.Api.Generator.Rest.Tests/GoldenTestData/Google.Apis.Translate.v2/Google.Apis.Translate.v2.cs
Google.Api.Generator.Rest.Tests/GoldenTestData/Google.Apis.Webfonts.v1/Google.Apis.Webfonts.v1.cs
Google.Api.Generator.Rest/Models/DataModel.cs
Google.Api.Generator.Rest/Models/DataPropertyModel.cs
Google.Api.Generator.Rest/Models/EnumMemberModel.cs
Google.Api.Generator.Rest/Models/MethodModel.cs
Google.Api.Generator.Rest/Models/PackageModel.cs
Google.Api.Generator.Rest/Models/ParameterModel.cs
Google.Api.Generator.Rest/Models/SchemaTypes.cs
Google.Api.Generator.Utils/Roslyn/XmlDoc.cs

With these in place, we're getting close to complete. There are still features missing, primarily media upload/download handling... but it's mostly tidy-up of odd little naming issues.

More REST data model population

---

Generator.sln
Google.Api.Generator.DiffSimplifier/Google.Api.Generator.DiffSimplifier.csproj
Google.Api.Generator.DiffSimplifier/Program.cs
Google.Api.Generator.Rest/CodeGenerator.cs
Google.Api.Generator.Rest/Models/DataModel.cs
Google.Api.Generator.Rest/Models/DataPropertyModel.cs
Google.Api.Generator.Rest/Models/EnumMemberModel.cs
Google.Api.Generator.Rest/Models/EnumModel.cs
Google.Api.Generator.Rest/Models/MethodModel.cs
Google.Api.Generator.Rest/Models/Naming.cs
Google.Api.Generator.Rest/Models/PackageModel.cs
Google.Api.Generator.Rest/Models/ParameterModel.cs
Google.Api.Generator.Rest/Models/ResourceModel.cs
Google.Api.Generator.Rest/Models/SchemaTypes.cs
Google.Api.Generator.Rest/Program.cs
Google.Api.Generator.Rest/StaticResources/NetStandard10Config.xml
Google.Api.Generator.Utils/Roslyn/Keywords.cs
Google.Api.Generator.Utils/SystemExtensions.cs
test-all-rest.sh

This is a bunch of miscellaneous fixes. Once this is in, there's still just a *little* bit of work to do on how data model classes are referenced, and then the C# part will be done. After that, we'll look at project files (which shouldn't be too bad).

More REST generator fixes

---

Google.Api.Generator.DiffSimplifier/Program.cs
Google.Api.Generator.Rest/CodeGenerator.cs
Google.Api.Generator.Rest/Features.cs
Google.Api.Generator.Rest/Models/PackageModel.cs

The generated files are identical to the Python-generated ones.

Generate csproj files more fully

---

.github/workflows/build.yml
Google.Api.Generator.Tests/InvocationTest.cs
Google.Api.Generator.Tests/Invoker.cs
global.json

Once this is in, we can change the branch protection and create
another PR that changes the badge and deletes the Travis build.

Add GitHub Actions workflow for push/pr

---

.gitignore
Google.Api.Generator.Rest/Models/MethodModel.cs
Google.Api.Generator.Rest/Models/PackageModel.cs

This gets back to parity with the Python generator

Fix REST generator

---

Google.Api.Generator.Rest/CodeGenerator.cs
Google.Api.Generator.Rest/Models/AuthScope.cs
Google.Api.Generator.Rest/Models/DataModel.cs
Google.Api.Generator.Rest/Models/DataPropertyModel.cs
Google.Api.Generator.Rest/Models/EnumMemberModel.cs
Google.Api.Generator.Rest/Models/EnumModel.cs
Google.Api.Generator.Rest/Models/MethodModel.cs
Google.Api.Generator.Rest/Models/PackageModel.cs
Google.Api.Generator.Rest/Models/ParameterModel.cs
Google.Api.Generator.Rest/Models/ResourceModel.cs

This is primarily about making properties private where possible (or removing them if they're only used once and it can be inlined) and giving more documentation. Definitely not the end, but progress.

First stages of refactoring

---

Google.Api.Generator.Tests/InvocationTest.cs
Google.Api.Generator/Program.cs

Correctly detect stdin with early eof

---

Google.Api.Generator.Utils/SourceFileContext.cs
Google.Api.Generator/CodeGenerator.cs

As per internal mail.
(Changes in tests are just because which namespaces are aliased has changed).

feat: Unaliased source file context now avoids all collisions.

---

Google.Api.Generator.Tests/ProtoTest.cs
Google.Api.Generator.Tests/ProtoTests/MethodSignatures/MethodSignaturesFakes.cs
Google.Api.Generator.Tests/ProtoTests/MethodSignatures/Testing.MethodSignatures.Tests/MethodSignaturesClientTest.g.cs
Google.Api.Generator.Tests/ProtoTests/MethodSignatures/Testing.MethodSignatures/MethodSignaturesClient.g.cs
Google.Api.Generator.Tests/ProtoTests/UnitTests/Testing.UnitTests.Tests/UnitTestsClientTest.g.cs
Google.Api.Generator/Generation/UnitTestCodeGeneration.cs

Fixnestedunittests

---

Google.Api.Generator.Tests/ProtoTests/MethodSignatures/Testing.MethodSignatures.Tests/MethodSignaturesClientTest.g.cs
Google.Api.Generator.Tests/ProtoTests/UnitTests/Testing.UnitTests.Tests/UnitTestsClientTest.g.cs
Google.Api.Generator.Tests/ProtoTests/UnitTests/UnitTests.proto
Google.Api.Generator.Tests/ProtoTests/UnitTests/UnitTestsFakes.cs
Google.Api.Generator/Generation/MethodDetails.cs
Google.Api.Generator/Generation/UnitTestCodeGeneration.cs

I can break the second commit up into more if you'd like.

Fix stack overflow

---

Google.Api.Generator/CodeGenerator.cs

Tested with AI Platform before and after proto patching.
Before the proto patch, it fails with an error message of:
> System.InvalidOperationException: The following resource name classes were created multiple times: ModelName, DatasetName
Also run the generator over all APIs in google-cloud-dotnet: no differences reported.

Fail generation if duplicate resource names are generated

---

Google.Api.Generator.Tests/ProtoTests/Snippets/Snippets.proto
Google.Api.Generator.Tests/ProtoTests/Snippets/SnippetsClientFakes.cs
Google.Api.Generator.Tests/ProtoTests/Snippets/Testing.Snippets.Snippets/SnippetsClientSnippets.g.cs
Google.Api.Generator.Tests/ProtoTests/Snippets/Testing.Snippets.StandaloneSnippets/SnippetsClient.OneOfMethodRequestObjectAsyncSnippet.g.cs
Google.Api.Generator.Tests/ProtoTests/Snippets/Testing.Snippets.StandaloneSnippets/SnippetsClient.OneOfMethodRequestObjectSnippet.g.cs
Google.Api.Generator/Generation/SnippetCodeGenerator.cs

Update snippet generator to only emit one field of a one-of

---

Google.Api.Generator.Tests/ProtoTests/RoutingHeaders/RoutingHeaders.proto
Google.Api.Generator.Tests/ProtoTests/RoutingHeaders/RoutingHeadersFakes.cs
Google.Api.Generator.Tests/ProtoTests/RoutingHeaders/Testing.RoutingHeaders/RoutingHeadersClient.g.cs
Google.Api.Generator/Generation/ServiceImplClientClassGenerator.cs

fix: Add WithGoogleRequestParam for server streaming calls

---

Google.Api.Generator/ProtoUtils/ResourceDetails.cs

If a resource_reference annotation is specified for a field of any
type other than string, we should throw an exception rather than
generating invalid code. This should allow presubmits to fail,
avoiding broken protos to be checked in.
Fixes #333.
Tested by:
- Demonstrating that the current Dialogflow protos fail generation (see below)
- Generating all (currently-generated-for-C#) APIs after fixing Dialogflow: no changes to current results
Failure with current Dialogflow proto:
>  System.InvalidOperationException: Field UpdateEnvironmentRequest.environment has a resource reference annotation, but is not a string field

Throw exception on invalid resource annotation

---

.github/renovate.json
Google.Api.Generator.Rest.Tests/GoldenTestData/Google.Apis.Storage.v1/Google.Apis.Storage.v1.cs
Google.Api.Generator.Rest.Tests/GoldenTestData/Google.Apis.Storage.v1/Google.Apis.Storage.v1.csproj
Google.Api.Generator.Rest.Tests/GoldenTestData/Google.Apis.Storage.v1/discovery.json
Google.Api.Generator.Rest.Tests/GoldenTestData/Google.Apis.Translate.v2/Google.Apis.Translate.v2.cs
Google.Api.Generator.Rest.Tests/GoldenTestData/Google.Apis.Translate.v2/Google.Apis.Translate.v2.csproj
Google.Api.Generator.Rest.Tests/GoldenTestData/Google.Apis.Translate.v2/discovery.json
Google.Api.Generator.Rest.Tests/GoldenTestData/Google.Apis.Webfonts.v1/Google.Apis.Webfonts.v1.cs
Google.Api.Generator.Rest.Tests/GoldenTestData/Google.Apis.Webfonts.v1/Google.Apis.Webfonts.v1.csproj
Google.Api.Generator.Rest.Tests/GoldenTestData/Google.Apis.Webfonts.v1/discovery.json
Google.Api.Generator.Rest.Tests/GoldenUnitTest.cs
Google.Api.Generator.Rest.Tests/TestResources.cs

These were already mostly-ready, but just needed some tweaking.
Additionally, set Renovate to ignore golden test data for both REST and GAPIC.

test: Implement "golden tests" for REST generator

---

.github/renovate.json
bazel_example/BUILD.bazel
bazel_example/WORKSPACE.bazel

- make bazel_example produce buildable code
- clean up and update the dependencies

chore: make bazel_example produce buildable code

---

Google.Api.Generator.Tests/ProtoTests/Basic/Testing.Basic/BasicClient.g.cs
Google.Api.Generator.Tests/ProtoTests/Basic/Testing.Basic/Testing.Basic.csproj
Google.Api.Generator.Tests/ProtoTests/Deprecated/Testing.Deprecated/DeprecatedClient.g.cs
Google.Api.Generator.Tests/ProtoTests/Keywords/Testing.Keywords/KeywordsClient.g.cs
Google.Api.Generator.Tests/ProtoTests/Lro/Testing.Lro/Testing.Lro.csproj
Google.Api.Generator.Tests/ProtoTests/MethodSignatures/Testing.MethodSignatures/MethodSignaturesClient.g.cs
Google.Api.Generator.Tests/ProtoTests/ResourceNames/Testing.ResourceNames/ResourceNamesClient.g.cs
Google.Api.Generator.Tests/ProtoTests/UnitTests/Testing.UnitTests/UnitTestsClient.g.cs
Google.Api.Generator/Generation/CsProjGenerator.cs
Google.Api.Generator/Generation/ServiceAbstractClientClassCodeGenerator.cs
Google.Api.Generator/Generation/ServiceBuilderCodeGenerator.cs
Google.Api.Generator/Google.Api.Generator.csproj

As ever, review one commit at a time

Self-signed JWT opt-in code

---

.github/renovate.json

chore: Disable the Renovate Dependency Dashboard

---

Google.Api.Generator/Generation/MetadataGenerator.cs

We assume the first service that was generated has the "right"
protobuf service, and discard any that have different protobuf
packages to that one.
So for example, when generating KMS and IAM, KMS first so only the
KMS services appear in the metadata.

fix: Trim gapic_metadata.json to appropriate services

---

Google.Api.Generator.Tests/Google.Api.Generator.Tests.csproj
Google.Api.Generator.Tests/ProtoTests/Basic.v1/Testing.Basic.V1/Testing.Basic.V1.csproj
Google.Api.Generator.Tests/ProtoTests/Lro/Testing.Lro/Testing.Lro.csproj
Google.Api.Generator.Utils/Google.Api.Generator.Utils.csproj
Google.Api.Generator/Generation/CsProjGenerator.cs
Google.Api.Generator/Google.Api.Generator.csproj

This updates the dependencies for GAX and gRPC.

chore: Update dependencies

---

Google.Api.Generator.Tests/ProtoTests/Basic.v1/Testing.Basic.V1.Tests/Testing.Basic.V1.Tests.csproj
Google.Api.Generator.Tests/ProtoTests/Mixins/Testing.Mixins.Tests/Testing.Mixins.Tests.csproj
Google.Api.Generator/Generation/CsProjGenerator.cs
Google.Api.Generator/Google.Api.Generator.csproj

chore: Update Moq dependency to 4.17.1

---

Google.Api.Generator.Tests/ProtoTests/Mixins/Testing.Mixins/Testing.Mixins.csproj
Google.Api.Generator/Generation/CsProjGenerator.cs
Google.Api.Generator/Google.Api.Generator.csproj

This should take care of #460 properly.

build: Increase Google.Cloud.Iam.V1 minor version

---

Google.Api.Generator.Tests/ProtoTests/Basic.v1/Testing.Basic.V1.GeneratedSnippets/Testing.Basic.V1.GeneratedSnippets.csproj
Google.Api.Generator.Tests/ProtoTests/Basic.v1/Testing.Basic.V1.Snippets/Testing.Basic.V1.Snippets.csproj
Google.Api.Generator.Tests/ProtoTests/Lro/Testing.Lro.GeneratedSnippets/Testing.Lro.GeneratedSnippets.csproj
Google.Api.Generator.Tests/ProtoTests/Lro/Testing.Lro.Snippets/Testing.Lro.Snippets.csproj
Google.Api.Generator/Generation/CsProjGenerator.cs
Google.Api.Generator/Google.Api.Generator.csproj

This will allow us to close #437

chore: Update System.Linq.Async dependency (in GAX v4)

---

Google.Api.Generator/Program.cs
rules_csharp_gapic/csharp_gapic.bzl

At the same time, this moves to using opt_args and opt_file_args to
generate cleaner protoc invocations.

fix: Fix the transport bazel arg (it's not a file)

---

.github/workflows/build.yml
Google.Api.Generator.IntegrationTests/Google.Api.Generator.IntegrationTests.csproj
Google.Api.Generator.Rest.Tests/Google.Api.Generator.Rest.Tests.csproj
Google.Api.Generator.Rest/Google.Api.Generator.Rest.csproj
Google.Api.Generator.Tests/Google.Api.Generator.Tests.csproj
Google.Api.Generator.Tests/Invoker.cs
Google.Api.Generator.Utils.Tests/Google.Api.Generator.Utils.Tests.csproj
Google.Api.Generator/Google.Api.Generator.csproj
global.json
rules_csharp_gapic/csharp_compiler.bzl
rules_csharp_gapic/csharp_compiler_repo.bzl

chore: Update to .NET 6

---

.allstar/binary_artifacts.yaml

chore: Have allstar ignore protoc artifacts.

---

Google.Api.Generator/CodeGenerator.cs

fix: Handle Boolean values in service configs

---

Google.Api.Generator/CodeGenerator.cs

There are various reasons why it's hard to pass the "correct" set of protos into the generator; this is a workaround which should at least improve matters.

fix: Only generate files for mixins if that's *all* we're generating

---

rules_csharp_gapic/csharp_compiler.bzl
rules_csharp_gapic/csharp_compiler_repo.bzl

First commit has the explanation.
I'm running a test against CloudBuild now. If it doesn't work, obviously I'll come back to this... just wanted to get your eyes on it early.

chore: Fix Bazel when running in Cloud Build

---

Google.Api.Generator/CodeGenerator.cs

Even if the "real" API is the first proto specified on the command line, protoc specifies protos in a dependency order which can cause issues: if a real API depends directly on a mix-in API, that ends up earlier in the generation order in protoc.
With this change, we assume the primary package is the first one for services we're actually going to emit, which doesn't include mix-ins (unless we're *only* generating mix-ins).
Testing this directly in the repo would be fiddly; instead this has been tested with the service where it was discovered, and I'm regenerating all APIs locally to check that it doesn't cause any other issues.

fix: Work out which proto package we're generating with more nuance

---

Google.Api.Generator.Tests/ProtoTests/ChildResource/Testing.ChildResource/ChildResourceResourceNames.g.cs
Google.Api.Generator.Tests/ProtoTests/Keywords/Testing.Keywords/KeywordsResourceNames.g.cs
Google.Api.Generator.Tests/ProtoTests/Lro/Testing.Lro/LroResourceNames.g.cs
Google.Api.Generator.Tests/ProtoTests/OptionalFields/Testing.OptionalFields/OptionalFieldsResourceNames.g.cs
Google.Api.Generator.Tests/ProtoTests/Paginated/Testing.Paginated/PaginatedResourceNames.g.cs
Google.Api.Generator.Tests/ProtoTests/PublishingSettings/Testing.PublishingSettings/PublishingSettingsResourceNames.g.cs
Google.Api.Generator.Tests/ProtoTests/ResourceNameSeparator/Testing.ResourceNameSeparator/ResourceNameSeparatorResourceNames.g.cs
Google.Api.Generator.Tests/ProtoTests/ResourceNames/Testing.ResourceNames/ResourceNamesResourceNames.g.cs
Google.Api.Generator.Tests/ProtoTests/ServerStreaming/Testing.ServerStreaming/ServerStreamingResourceNames.g.cs
Google.Api.Generator.Tests/ProtoTests/Showcase/Google.Showcase.V1Beta1/IdentityResourceNames.g.cs
Google.Api.Generator.Tests/ProtoTests/Showcase/Google.Showcase.V1Beta1/MessagingResourceNames.g.cs
Google.Api.Generator.Tests/ProtoTests/Showcase/Google.Showcase.V1Beta1/SequenceResourceNames.g.cs
Google.Api.Generator.Tests/ProtoTests/Showcase/Google.Showcase.V1Beta1/TestingResourceNames.g.cs
Google.Api.Generator.Tests/ProtoTests/Snippets/Testing.Snippets/SnippetsResourceNames.g.cs
Google.Api.Generator/Generation/ResourceNamesGenerator.cs

Implementation in first commit; test changes in second.

fix: Generate appropriate XML documentation for resource name operators

---

Google.Api.Generator.Rest.Tests/GoldenTestData/Google.Apis.CloudSupport.v2/Google.Apis.CloudSupport.v2.cs
Google.Api.Generator.Rest.Tests/GoldenTestData/Google.Apis.CloudSupport.v2/Google.Apis.CloudSupport.v2.csproj
Google.Api.Generator.Rest.Tests/GoldenTestData/Google.Apis.CloudSupport.v2/discovery.json
Google.Api.Generator.Rest.Tests/GoldenUnitTest.cs

This should have been in #657.

tests: Add CloudSupport test in REST generator

---

Google.Api.Generator.Rest.Tests/GoldenTestData/Google.Apis.CloudSupport.v2/Google.Apis.CloudSupport.v2.cs
Google.Api.Generator.Rest.Tests/GoldenTestData/Google.Apis.DataprocMetastore.v1/Google.Apis.DataprocMetastore.v1.cs
Google.Api.Generator.Rest.Tests/GoldenTestData/Google.Apis.DataprocMetastore.v1/Google.Apis.DataprocMetastore.v1.csproj
Google.Api.Generator.Rest.Tests/GoldenTestData/Google.Apis.DataprocMetastore.v1/discovery.json
Google.Api.Generator.Rest.Tests/GoldenTestData/Google.Apis.ManufacturerCenter.v1/Google.Apis.ManufacturerCenter.v1.cs
Google.Api.Generator.Rest.Tests/GoldenTestData/Google.Apis.Storage.v1/Google.Apis.Storage.v1.cs
Google.Api.Generator.Rest.Tests/GoldenTestData/Google.Apis.Translate.v2/Google.Apis.Translate.v2.cs
Google.Api.Generator.Rest.Tests/GoldenTestData/Google.Apis.Webfonts.v1/Google.Apis.Webfonts.v1.cs
Google.Api.Generator.Rest.Tests/GoldenUnitTest.cs
Google.Api.Generator.Rest/Models/MethodModel.cs
Google.Api.Generator.Rest/Models/ParameterModel.cs
Google.Api.Generator.Utils/Roslyn/RoslynExtensions.cs

Definitely review one commit at a time - I think I'd like to merge it this way, too.

feat: Escape "service" parameters in REST generator

---

Google.Api.Generator.IntegrationTests/README.md

docs: Add a README to describe how to run the integration tests

---

Google.Api.Generator.Rest.Tests/GoldenTestData/Google.Apis.Assuredworkloads.v1/Google.Apis.Assuredworkloads.v1.cs
Google.Api.Generator.Rest.Tests/GoldenTestData/Google.Apis.Assuredworkloads.v1/Google.Apis.Assuredworkloads.v1.csproj
Google.Api.Generator.Rest.Tests/GoldenTestData/Google.Apis.Assuredworkloads.v1/discovery.json
Google.Api.Generator.Rest.Tests/GoldenTestData/Google.Apis.Calendar.v3/Google.Apis.Calendar.v3.cs
Google.Api.Generator.Rest.Tests/GoldenTestData/Google.Apis.Calendar.v3/Google.Apis.Calendar.v3.csproj
Google.Api.Generator.Rest.Tests/GoldenTestData/Google.Apis.Calendar.v3/discovery.json
Google.Api.Generator.Rest.Tests/GoldenTestData/Google.Apis.CloudSupport.v2/Google.Apis.CloudSupport.v2.cs
Google.Api.Generator.Rest.Tests/GoldenTestData/Google.Apis.DataprocMetastore.v1/Google.Apis.DataprocMetastore.v1.cs
Google.Api.Generator.Rest.Tests/GoldenTestData/Google.Apis.ManufacturerCenter.v1/Google.Apis.ManufacturerCenter.v1.cs
Google.Api.Generator.Rest.Tests/GoldenTestData/Google.Apis.Storage.v1/Google.Apis.Storage.v1.cs
Google.Api.Generator.Rest.Tests/GoldenUnitTest.cs
Google.Api.Generator.Rest/Google.Api.Generator.Rest.csproj
Google.Api.Generator.Rest/Models/DataPropertyModel.cs
Google.Api.Generator.Rest/Models/ParameterModel.cs
Google.Api.Generator.Utils/Roslyn/RoslynBuilder.cs
Google.Api.Generator.Utils/Roslyn/RoslynExtensions.cs

This single PR fixes #700 and #701.
It makes #704 and #705 obsolete. (It's basically a rewrite.)
The last commit is the one requiring most concerted review. I'm currently regenerating and rebuilding all packages in google-api-dotnet-client to check for unexpected problems.

fix: Improvements to date/time handling

---

Google.Api.Generator/CodeGenerator.cs
Google.Api.Generator/Logging.cs
Google.Api.Generator/Program.cs

This is very quick and dirty, but is enough to help diagnose issues. Without this showing that the generator is actually quite quick, I wouldn't have worked out what was *actually* taking the time in our local generator script...
(We can do something similar for the REST generator at some point.)
Fixes #724.

feat: Logging in the GAPIC generator

---

Google.Api.Generator.Rest.Tests/GoldenTestData/Google.Apis.Assuredworkloads.v1/Google.Apis.Assuredworkloads.v1.csproj
Google.Api.Generator.Rest.Tests/GoldenTestData/Google.Apis.Calendar.v3/Google.Apis.Calendar.v3.csproj
Google.Api.Generator.Rest.Tests/GoldenTestData/Google.Apis.CloudSupport.v2/Google.Apis.CloudSupport.v2.csproj
Google.Api.Generator.Rest.Tests/GoldenTestData/Google.Apis.Contentwarehouse.v1/Google.Apis.Contentwarehouse.v1.csproj
Google.Api.Generator.Rest.Tests/GoldenTestData/Google.Apis.DataprocMetastore.v1/Google.Apis.DataprocMetastore.v1.csproj
Google.Api.Generator.Rest.Tests/GoldenTestData/Google.Apis.ManufacturerCenter.v1/Google.Apis.ManufacturerCenter.v1.csproj
Google.Api.Generator.Rest.Tests/GoldenTestData/Google.Apis.Storage.v1/Google.Apis.Storage.v1.csproj
Google.Api.Generator.Rest.Tests/GoldenTestData/Google.Apis.Translate.v2/Google.Apis.Translate.v2.csproj
Google.Api.Generator.Rest.Tests/GoldenTestData/Google.Apis.Webfonts.v1/Google.Apis.Webfonts.v1.csproj
Google.Api.Generator.Rest/Models/PackageModel.cs

See https://github.com/googleapis/google-api-dotnet-client/issues/2561 for more details.

feat: Update target platforms for REST libraries

---

Google.Api.Generator.Tests/ProtoTests/PublishingSettings/PublishingSettings.proto
Google.Api.Generator.Tests/ProtoTests/PublishingSettings/PublishingSettingsFakes.cs
Google.Api.Generator.Tests/ProtoTests/PublishingSettings/ServiceConfig.yaml
Google.Api.Generator.Tests/ProtoTests/PublishingSettings/Testing.PublishingSettings.GeneratedSnippets/RenamedServiceNameClient.AMethodRequestObjectAsyncSnippet.g.cs
Google.Api.Generator.Tests/ProtoTests/PublishingSettings/Testing.PublishingSettings.GeneratedSnippets/RenamedServiceNameClient.AMethodRequestObjectSnippet.g.cs
Google.Api.Generator.Tests/ProtoTests/PublishingSettings/Testing.PublishingSettings.GeneratedSnippets/ServiceWithHandwrittenSignaturesClient.AMethodRequestObjectSnippet.g.cs
Google.Api.Generator.Tests/ProtoTests/PublishingSettings/Testing.PublishingSettings.GeneratedSnippets/ServiceWithMethodSettingsClient.BidiStreamingAutoPopulatedSnippet.g.cs
Google.Api.Generator.Tests/ProtoTests/PublishingSettings/Testing.PublishingSettings.GeneratedSnippets/ServiceWithMethodSettingsClient.LroAutoPopulatedRequestObjectAsyncSnippet.g.cs
Google.Api.Generator.Tests/ProtoTests/PublishingSettings/Testing.PublishingSettings.GeneratedSnippets/ServiceWithMethodSettingsClient.LroAutoPopulatedRequestObjectSnippet.g.cs
Google.Api.Generator.Tests/ProtoTests/PublishingSettings/Testing.PublishingSettings.GeneratedSnippets/ServiceWithMethodSettingsClient.PaginatedAutoPopulatedRequestObjectAsyncSnippet.g.cs
Google.Api.Generator.Tests/ProtoTests/PublishingSettings/Testing.PublishingSettings.GeneratedSnippets/ServiceWithMethodSettingsClient.PaginatedAutoPopulatedRequestObjectSnippet.g.cs
Google.Api.Generator.Tests/ProtoTests/PublishingSettings/Testing.PublishingSettings.GeneratedSnippets/ServiceWithMethodSettingsClient.ServerStreamingAutoPopulatedRequestObjectSnippet.g.cs
Google.Api.Generator.Tests/ProtoTests/PublishingSettings/Testing.PublishingSettings.GeneratedSnippets/ServiceWithMethodSettingsClient.UnaryAutoPopulatedRequestObjectAsyncSnippet.g.cs
Google.Api.Generator.Tests/ProtoTests/PublishingSettings/Testing.PublishingSettings.GeneratedSnippets/ServiceWithMethodSettingsClient.UnaryAutoPopulatedRequestObjectSnippet.g.cs
Google.Api.Generator.Tests/ProtoTests/PublishingSettings/Testing.PublishingSettings.GeneratedSnippets/snippet_metadata_testing.publishingsettings.json
Google.Api.Generator.Tests/ProtoTests/PublishingSettings/Testing.PublishingSettings.Snippets/RenamedServiceNameClientSnippets.g.cs
Google.Api.Generator.Tests/ProtoTests/PublishingSettings/Testing.PublishingSettings.Snippets/ServiceWithHandwrittenSignaturesClientSnippets.g.cs
Google.Api.Generator.Tests/ProtoTests/PublishingSettings/Testing.PublishingSettings.Snippets/ServiceWithMethodSettingsClientSnippets.g.cs
Google.Api.Generator.Tests/ProtoTests/PublishingSettings/Testing.PublishingSettings/PackageApiMetadata.g.cs
Google.Api.Generator.Tests/ProtoTests/PublishingSettings/Testing.PublishingSettings/ServiceCollectionExtensions.g.cs
Google.Api.Generator.Tests/ProtoTests/PublishingSettings/Testing.PublishingSettings/ServiceWithMethodSettingsClient.g.cs
Google.Api.Generator.Tests/ProtoTests/PublishingSettings/Testing.PublishingSettings/Testing.PublishingSettings.csproj
Google.Api.Generator.Utils/Roslyn/RoslynExtensions.cs
Google.Api.Generator/CodeGenerator.cs
Google.Api.Generator/Generation/MethodDetails.cs
Google.Api.Generator/Generation/ServiceDetails.cs
Google.Api.Generator/Generation/ServiceMethodGenerator.cs
Google.Api.Generator/Generation/SnippetCodeGenerator.cs
Google.Api.Generator/Google.Api.Generator.csproj

Very much a "review one commit at a time" - but probably ignore the third commit entirely.
Fixes b/324255261

feat: Generate field auto-population

---

Google.Api.Generator.Rest.Tests/Google.Api.Generator.Rest.Tests.csproj
Google.Api.Generator.Rest/Google.Api.Generator.Rest.csproj

And remove the temporary Google.Apis dependency from tests.

build: Update Google.Apis.Discovery.v1 dependency.

---

Google.Api.Generator/CodeGenerator.cs

(Repeating the same namespace over and over doesn't give any information...)

chore: Make GAPIC generator logging more helpful

---

.github/CODEOWNERS
.github/blunderbuss.yml

The @googleapis/cloud-libraries-dotnet group is synced from an internal group.

chore: Update ownership

---

Google.Api.Generator.Rest/CodeGenerator.cs
Google.Api.Generator.Rest/Program.cs
Google.Api.Generator.Utils/Google.Api.Generator.Utils.csproj
Google.Api.Generator.Utils/Logging.cs
Google.Api.Generator/CodeGenerator.cs
Google.Api.Generator/Program.cs

(This was used to help determine where the time was going for REST generation.)

chore: Move Logging class into utility project, and add very basic REST logging

---

Google.Api.Generator.Rest.Tests/GoldenTestData/Google.Apis.Assuredworkloads.v1/Google.Apis.Assuredworkloads.v1.csproj
Google.Api.Generator.Rest.Tests/GoldenTestData/Google.Apis.Calendar.v3/Google.Apis.Calendar.v3.csproj
Google.Api.Generator.Rest.Tests/GoldenTestData/Google.Apis.CloudSupport.v2/Google.Apis.CloudSupport.v2.csproj
Google.Api.Generator.Rest.Tests/GoldenTestData/Google.Apis.Contentwarehouse.v1/Google.Apis.Contentwarehouse.v1.csproj
Google.Api.Generator.Rest.Tests/GoldenTestData/Google.Apis.DataprocMetastore.v1/Google.Apis.DataprocMetastore.v1.csproj
Google.Api.Generator.Rest.Tests/GoldenTestData/Google.Apis.ManufacturerCenter.v1/Google.Apis.ManufacturerCenter.v1.csproj
Google.Api.Generator.Rest.Tests/GoldenTestData/Google.Apis.Storage.v1/Google.Apis.Storage.v1.csproj
Google.Api.Generator.Rest.Tests/GoldenTestData/Google.Apis.Translate.v2/Google.Apis.Translate.v2.csproj
Google.Api.Generator.Rest.Tests/GoldenTestData/Google.Apis.Webfonts.v1/Google.Apis.Webfonts.v1.csproj
Google.Api.Generator.Rest/Models/PackageModel.cs

feat: Generate more useful descriptions for REST packages

---

Google.Api.Generator.Tests/ProtoTest.cs
Google.Api.Generator.Tests/ProtoTests/PublishingSettings/Testing.PublishingSettings/PackageApiMetadata.g.cs
Google.Api.Generator.Tests/ProtoTests/PublishingSettings/Testing.PublishingSettings/ServiceCollectionExtensions.g.cs

(These shouldn't have been removed, as settings can affect these classes.)
Fixes b/332845188

tests: Reinstate DI extensions and metadata in publishing settings tests

---

Google.Api.Generator/CodeGenerator.cs

Towards #652.
There are three potential levels of enforcement:
- Level 0 (this commit): log warnings and errors, but don't actually make the generator fail
- Level 1: fail if a service or RPC has no comment, as that will definitely break the generated GAPIC code
- Level 2: fail if *any* comment is missing
Level 2 would be a nice ideal, but level 1 is more practical. This commit doesn't go that far, as we suspect there will be a number of APIs where that would fail. The first step should be to generate as many APIs as we can (not just those in google-cloud-dotnet) and find out how many *would* fail. Ideally, we can then get those fixed, and turn on level 1 enforcement.

feat: Log warnings and errors on missing proto comments

---

Google.Api.Generator.Tests/ProtoTests/ResourceNames/ResourceNames.proto
Google.Api.Generator.Tests/ProtoTests/ResourceNames/ResourceNamesFakes.cs
Google.Api.Generator.Tests/ProtoTests/ResourceNames/Testing.ResourceNames/ResourceNamesResourceNames.g.cs
Google.Api.Generator.Tests/ProtoTests/Showcase/Google.Showcase.V1Beta1/MessagingResourceNames.g.cs
Google.Api.Generator.Tests/ProtoTests/Showcase/Google.Showcase.V1Beta1/TestingResourceNames.g.cs
Google.Api.Generator/Generation/ResourceNamesGenerator.cs
Google.Api.Generator/ProtoUtils/ProtoExtensions.cs
Google.Api.Generator/ProtoUtils/ResourceDetails.cs

Currently generating google-cloud-dotnet so I can post a diff there (although it'll also include all the reordering).
Fixes b/339353198.

feat: Generate properties for nested resource reference fields

---

Google.Api.Generator.Tests/ProtoTests/Lro/Testing.Lro/Testing.Lro.csproj
Google.Api.Generator.Tests/ProtoTests/Mixins/Testing.Mixins/Testing.Mixins.csproj
Google.Api.Generator.Tests/ProtoTests/Showcase/Google.Showcase.V1Beta1/Google.Showcase.V1Beta1.csproj
Google.Api.Generator/Generation/CsProjGenerator.cs
Google.Api.Generator/Google.Api.Generator.csproj

chore: Update all mixins in the generator and its generated projects

---

Google.Api.Generator.Rest.Tests/GoldenTestData/Google.Apis.Assuredworkloads.v1/Google.Apis.Assuredworkloads.v1.csproj
Google.Api.Generator.Rest.Tests/GoldenTestData/Google.Apis.Calendar.v3/Google.Apis.Calendar.v3.csproj
Google.Api.Generator.Rest.Tests/GoldenTestData/Google.Apis.CloudRun.v1/Google.Apis.CloudRun.v1.csproj
Google.Api.Generator.Rest.Tests/GoldenTestData/Google.Apis.CloudSupport.v2/Google.Apis.CloudSupport.v2.csproj
Google.Api.Generator.Rest.Tests/GoldenTestData/Google.Apis.DataprocMetastore.v1/Google.Apis.DataprocMetastore.v1.csproj
Google.Api.Generator.Rest.Tests/GoldenTestData/Google.Apis.ManufacturerCenter.v1/Google.Apis.ManufacturerCenter.v1.csproj
Google.Api.Generator.Rest.Tests/GoldenTestData/Google.Apis.Storage.v1/Google.Apis.Storage.v1.csproj
Google.Api.Generator.Rest.Tests/GoldenTestData/Google.Apis.Translate.v2/Google.Apis.Translate.v2.csproj
Google.Api.Generator.Rest.Tests/GoldenTestData/Google.Apis.Webfonts.v1/Google.Apis.Webfonts.v1.csproj
Google.Api.Generator.Rest/Models/PackageModel.cs

This is the generator counterpart of https://github.com/googleapis/google-api-dotnet-client/pull/2776

feat: Remove reference assemblies and SourceLink for REST

---

Google.Api.Generator.Tests/ProtoTests/Paginated/Testing.Paginated/PaginatedClient.g.cs
Google.Api.Generator.Tests/ProtoTests/Showcase/Google.Showcase.V1Beta1/MessagingClient.g.cs
Google.Api.Generator.Utils/Roslyn/RoslynExtensions.cs
Google.Api.Generator/Generation/ServiceMethodGenerator.Signatures.cs

I'm going to run this locally against everything in google-cloud-dotnet, and build the result.

fix: Conditionally specify page token and page size in pagination

---

Directory.Build.props
Directory.Packages.props
Google.Api.Generator.IntegrationTests/Google.Api.Generator.IntegrationTests.csproj
Google.Api.Generator.Rest.Tests/Google.Api.Generator.Rest.Tests.csproj
Google.Api.Generator.Rest/Google.Api.Generator.Rest.csproj
Google.Api.Generator.Testing/Google.Api.Generator.Testing.csproj
Google.Api.Generator.Tests/Google.Api.Generator.Tests.csproj
Google.Api.Generator.Tests/ProtoTests/Directory.Build.props
Google.Api.Generator.Utils.Tests/Google.Api.Generator.Utils.Tests.csproj
Google.Api.Generator.Utils/Formatting/WhitespaceFormatter.cs
Google.Api.Generator.Utils/Google.Api.Generator.Utils.csproj
Google.Api.Generator/Google.Api.Generator.csproj

(Non-urgent - don't bother reviewing until after holidays.)

chore: Adopt centralized package management

---

Directory.Packages.props
Google.Api.Generator/CodeGenerator.cs
Google.Api.Generator/Google.Api.Generator.csproj

chore: Update to latest protobuf to use new helpers
